### ISSUE TITLE
i'm making LightBulb with mqtt and need to get state of device

### ISSUE THREAD

**Issue by gerswin** [ikalchev/HAP-python#10]
this is my code, can u explain me how to get the status of device. 
```

import logging

from pyhap.accessory import Accessory, Category
import pyhap.loader as loader
import paho.mqtt.subscribe as subscribe
import paho.mqtt.publish as publish

auth = {
  'username':"",
  'password':""
}


class LightBulb(Accessory):

    category = Category.LIGHTBULB

    def __init__(self, *args,**kwargs):
        super(LightBulb, self).__init__(*args, **kwargs)

        


    def __setstate__(self, state):
        self.__dict__.update(state)
       

    def set_bulb(self, value):
        print(value) 
        publish.single("inTopic",
        payload=value,
        hostname="localhost",
        client_id="screen",
        auth=auth,
        retain=False,
        port=1883)

    def _set_services(self):
        super(LightBulb, self)._set_services()

        bulb_service = loader.get_serv_loader().get("Lightbulb")
        self.add_service(bulb_service)
        bulb_service.get_characteristic("On").setter_callback = self.set_bulb

    def stop(self):
        super(LightBulb, self).stop()
        
```

**Comment by ikalchev** [comment]
What do you mean by status? Do you mean the value of the characteristic “On”? If so:

```python 
C = self.get_service(“Lightbulb”).get_characteristic(“On”)
C.get_value()
```

**Comment by gerswin** [comment]
i need to know if is on or off

**Comment by ikalchev** [comment]
`get_value` gets you that - true for on and false for off. This same value is also passed to you in `set_bulb`.

Does that answer your question or did I misunderstood something?

**Comment by gerswin** [comment]
I have my mqtt server that can control the devices outside the homekit, so if I turn off a light from another device in homekit it stays on. there is some way to update the status in homekit

**Comment by ikalchev** [comment]
You need to set the value of the characteristic. This is done like:

```python
C = self.get_service(“Lightbulb”).get_characteristic(“On”)
new_value = true
C.set_value(new_value)
# method is set_value(value, should_notify=true)
# the second argument indicates whether to send an update to iOS clients (i.e. the Home app)
# of the new value. This is true by default, which is what you want.
```

Let me know if this is what you want :)

**Comment by ikalchev** [comment]
@gerswin Any updates here? Did you manage to do what you wanted?

**Comment by gerswin** [comment]
i'm using with sentinel

    def run(self):
        while not self.run_sentinel.wait(10):
            print(1)
            #m = subscribe.simple(['/34:34:34/status'], hostname="localhost", retained=True, msg_count=1)
            #self.get_service("Lightbulb").get_characteristic("On").set_value(m.payload)



Exception happened during processing of request from ('192.168.0.11', 51619)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/gerswin/HAP-python/pyhap/hap_server.py", line 779, in finish_request
    self.RequestHandlerClass(sock, client_addr, self, self.accessory_handler)
  File "/home/gerswin/HAP-python/pyhap/hap_server.py", line 141, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 420, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/home/gerswin/HAP-python/pyhap/hap_server.py", line 202, in dispatch
    getattr(self, self.HANDLERS[self.command][path])()
  File "/home/gerswin/HAP-python/pyhap/hap_server.py", line 485, in handle_accessories
    data = json.dumps(hap_rep).encode("utf-8")
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

**Comment by gerswin** [comment]
it's working thanks!

**Comment by ikalchev** [comment]
No worries, let me know if you need more help.
