### ISSUE TITLE
Persist accessories in a different format than pickle

### ISSUE THREAD

**Issue by ikalchev** [ikalchev/HAP-python#12]
The new format should allow new HAP-python versions to understand state from an older version, removing the need to `rm accessory.pickle` after updating HAP-python and potentially requiring less space.

**Comment by helmsman35** [comment]
+1

**Comment by ikalchev** [comment]
Almost there, sometime tomorrow probably :)

**Comment by ikalchev** [comment]
@helmsman35 Done! Take a look at main.py for the new workflow. The init is now called on restart (this is, you still need to create your accessory hierarchy and pass it to the driver).
