### ISSUE TITLE
How to assign a unique topic or ID to an accessory.

### ISSUE THREAD

**Issue by p000** [ikalchev/HAP-python#134]

**Comment by p000** [comment]
I tried adding ``` aid ``` when creating the accessory, but its throwing error.
Is it possible to store 16 char value in ``` aid ``` so that I'll know which device is triggered.

**Comment by ikalchev** [comment]
> I tried adding aid when creating the accessory, but its throwing error.

Are you getting:

```
File "/Users/ivankalchev/Dev/github/HAP-python/pyhap/accessory_driver.py", line 327, in add_accessory
    raise ValueError("Top-level accessory must have the AID == 1.")
ValueError: Top-level accessory must have the AID == 1.
```

If you have a standalone accessory, it must have an AID equal to 1 - this is required by the apple protocol. If you have a bridge, then the bridge must have an AID equal to 1, and all accessories in the bridge can be whatever you like. Quoting Apple's spec:

> Instance IDs are numbers with a range of [1, 18446744073709551615]

May I ask what are you trying to achieve? Maybe we can help

**Comment by ikalchev** [comment]
Reopen if you find an issue here. Keep the conversation here if needed :)

**Comment by p000** [comment]
I wanted to attach unique topic to every accessory in order to control.
