### ISSUE TITLE
Home App "Couldn't add Bridge" error

### ISSUE THREAD

**Issue by KyleLeneau** [ikalchev/HAP-python#137]
Hello,

I am not sure the best way to report this issue to you but I have run across something that is very similar to this issue: https://github.com/home-assistant/home-assistant/issues/12868

From the logs it looks like everything is pairing correctly but the Home app is reporting that it can't connect to the accessory afterwards. I am using the latest version of the distribution from PyPi (2.2.2) with no luck and have tried from source and modified the MDNS advertisement like the issue above mentioned.

I have had this project working in the past on a 1.x version but have decided to upgrade to the latest.

I am also still in the development phase and am running my app on a MacBook Pro. Both phone and laptop are on the same network as well. What is puzzling is that I don't see any errors from the HAP side.

Any help or direction would be super helpful. I am happy to help share what I am working on and contribute back to the examples based on the changes in the API I am encountering as well.

Thanks!

**Comment by cdce8p** [comment]
Have you tried setting the logging level to `DEBUG`?

You mentioned the Home Assistant issue thread. It might be helpful to take a look at https://github.com/home-assistant/home-assistant/issues/14567 as well.

**Comment by KyleLeneau** [comment]
I just restarted my machine and updated the `accessory_driver.py` file (https://raw.githubusercontent.com/cdce8p/HAP-python/5f6f7d4589b5a64b3159475c7701d901a7d01933/pyhap/accessory_driver.py) and got the same error again.

I also have my applications log level set to `DEBUG` and see the debug messages from my module and pyhap but no errors in the console.

I am starting my app as `vent/bin/python main.py` as an FYI

---

Interesting thing I just found. I have a bridge that I am trying to add that has many accessories, when I don't add any accessories in my program I can successfully pair the bridge alone. Something about the child accessories is screwing up up instead...

**Comment by KyleLeneau** [comment]
I just got it working now with the new driver. I was setting the aid on the child accessories to a UUID string (primary ID of what I am backing). I am going to try the old 2.2.2 version again and see if it will still work for me without the workaround.

**Comment by KyleLeneau** [comment]
Another update, I got it working with the `accessory_driver` from the original source and distribution.

**Comment by ikalchev** [comment]
Hi @KyleLeneau and sorry for the delay. Just to make sure I get the issue correctly: you were setting the AID to a UUID string and now when you set it to an uint it works, correct? (AID or IIDs should be non-negative integers per the HAP spec). If this is the whole issue, I guess I need to update the docs or check the type of the passed AID.

**Comment by ikalchev** [comment]
Glad to hear you got it working. I will add a type check so this can be caught earlier
