### ISSUE TITLE
How to re-add accessories?

### ISSUE THREAD

**Issue by ilyamordasov** [ikalchev/HAP-python#139]
If I remove all accessories from HomeKit and try to add the new one, I can't see the pairing code. If I reboot HAP-bridge it's waiting for the accesories from HomeKit.

`INFO:pyhap.accessory_driver:Loading Accessory state from accessory.state
INFO:pyhap.accessory_driver:Starting the event loop
INFO:pyhap.accessory_driver:Starting accessory Bridge on address 10.0.50.41, port 51826.`

For example in Homebridge you have to delete 2 folders from .homebridge to initialise again accessories

**Comment by ikalchev** [comment]
To just start anew, delete `accessory.state`  and let me know if you get the code again. 

As for showing the code after a reboot, let me get back to you tomorrow.

**Comment by ilyamordasov** [comment]
yep, it works! thanks
