### ISSUE TITLE
Possible problem in iOS 11

### ISSUE THREAD

**Issue by sergiookey** [ikalchev/HAP-python#14]
Congratulations for your great work. 

I add all accessory to homekit and I work perfectly but when I restart process, my iPhone with iOS 11.2.1 not reconnect accesories. The accessories have simbol (!). What can I do?

Thank you very much

**Comment by gerswin** [comment]
do you delete accessory.pickle and try again?

**Comment by sergiookey** [comment]
I delete file and try again, but not works.

**Comment by sergiookey** [comment]
My mistake was to create the bridge at each process start instead of loading the file configuration. This file has the status of the accessories and the necessary data for reconnection. Thank you very much for the help. Great job.

**Comment by ikalchev** [comment]
@sergiookey I’m glad you find the project useful and that you solved your issue :)
