### ISSUE TITLE
 ValueError("Duplicate AID found when attempting to add accessory") ValueError: Duplicate AID found when attempting to add accessory

### ISSUE THREAD

**Issue by gerswin** [ikalchev/HAP-python#15]
in last update bridge mode is not working. 
tested with main.py

**Comment by gerswin** [comment]
def __init__(self, display_name, mac=None, pincode=None, iid_manager=None):
        #aid = STANDALONE_AID

i just comment the first line and is working again

**Comment by ikalchev** [comment]
Very very sorry about that.

The problem was that AID in Accessory init is now STANDALONE AID and not None. Just added aid=2 for the contained accessory in main.py. (pypi package also fixed)

Thanks!
