### ISSUE TITLE
Perpetual Updating and No Response 

### ISSUE THREAD

**Issue by LasCabos** [ikalchev/HAP-python#153]
After pulling your latest changes (commit addb6aa) any sensors or bridges added are in a perpetual state of updating and no response as indicated in the HomeKit iOS App. I have tested this on iOS versions 11.0.3, 11.4.1 and 12.0.0 using your main.py using a bridge setup with 2 temperature sensors and a single lightBulb accessory. On occasion a request will be received by the iOS device but revert to the updating and eventually no response state. 

I pulled commit 5e8a981 and ran with the 3 accessory bridge in main.py. Connecting and updating with iOS 12 works fine. The problem appears to have happened between these two commits.

**Comment by ikalchev** [comment]
Hi and thanks for reporting this.

I got a look at it and it seems that the issue is actually caused by https://github.com/ikalchev/HAP-python/commit/6272c7b2a3e04db93b53b920e27e134ac7a48a87

I will address this today/tomorrow.

**Comment by ignalex** [comment]
just pulled from your last commit. no changes for me. (RPi 2). hanging in updating state. 
from pip's (old) pyhap works ok. 
a few reports 
DEBUG - Could not send event to ('192.168.1.10', 49376), probably stale socket.
and a few 
DEBUG - Connection timeout

**Comment by ikalchev** [comment]
So if understand correctly, you have
- latest available from pip works
- latest available from the dev branch doesn't

Also which iOS v is this?

**Comment by ignalex** [comment]
> So if understand correctly, you have
> 
> * latest available from pip works
> * latest available from the dev branch doesn't
> 
> Also which iOS v is this?

correct. 
iOS 12. 
I got collected 2 sets of logs from pip's working code and the one from git dev. 
hope it will give you some ideas :)

[ignalex.zip](https://github.com/ikalchev/HAP-python/files/2408688/ignalex.zip)

**Comment by ikalchev** [comment]
Thanks for that. But the logs don't seem to be from latest. There is a missing debug message in the logs. I expected to see this https://github.com/ikalchev/HAP-python/blob/dev/pyhap/hap_server.py#L517

From HAP_server_dev_not_working
```
09-23-2018 09:55:16 PM - DEBUG - Request PUT from address '('192.168.1.10', 49420)' for path '/characteristics'.
<<< Expected debug message here
09-23-2018 09:55:16 PM - INFO - 192.168.1.10 - "PUT /characteristics HTTP/1.1" 207 -
```

Also, the response to the PUT request above should be `204 No Content`, but we see `207 Multi-Status` in the logs. This was changed in 6272c7b.

Can you re-check the actual versions used? I would expect something like:
```
DEBUG:pyhap.hap_server:Request PUT from address '('192.168.1.114', 56252)' for path '/characteristics'.
DEBUG:pyhap.hap_server:Set characteristics content: {'characteristics': [{'aid': 1, 'iid': 9, 'ev': True}]}
INFO:pyhap.hap_server:192.168.1.114 - "PUT /characteristics HTTP/1.1" 204 -
```

**Comment by LasCabos** [comment]
I will test and post here but it will have to wait until tomorrow, Sept 24, 2018. My original issue was a result of running on Raspberry Pi 3 B+.

**Comment by ignalex** [comment]
![image](https://user-images.githubusercontent.com/7232721/45928132-037d5800-bf82-11e8-93ba-fc0583310aa1.png)
hmm . got the blob you sent in the code. 
the location of dev is the recent git version 
![image](https://user-images.githubusercontent.com/7232721/45928275-522bf180-bf84-11e8-9aa7-0acced6c9cdd.png)
so I am pretty sure I am using the l have latest code in this location (got it pulled after your go-ahead comment) 
![image](https://user-images.githubusercontent.com/7232721/45928305-cb2b4900-bf84-11e8-9914-4ea585558a44.png)

is there any way I can check version? 
pyhap.__version__  attrib is not set. ...

**Comment by ignalex** [comment]
hey Ivan, 
my apologies. you are right. was imported  partly from the pip's install. 
works well,  no issues. also attaching log with ' Set characteristics content'  
[HAP_server.zip](https://github.com/ikalchev/HAP-python/files/2408756/HAP_server.zip)

**Comment by ikalchev** [comment]
Glad to hear that! And sorry for the delay on this :)

**Comment by LasCabos** [comment]
Tested with RPI 3 B+,  python 3.5 and iOS 12 using the NeoPixelLightStrip and your fix is working great. Thanks for all your efforts with this project! Its awesome!

**Comment by ikalchev** [comment]
Thanks! I am very happy to hear that.
