### ISSUE TITLE
New Accessories - Faucet, Valve, Sprinklers, ...

### ISSUE THREAD

**Issue by cdce8p** [ikalchev/HAP-python#156]
@ikalchev Can you run the script to see if they are available?
If not, I have found another project that has already implemented them, so I could reverse engineer it from there.

https://github.com/maximkulkin/esp-homekit/commit/f064988e023f705908e815b90b35ecd9abff52cf
https://github.com/maximkulkin/esp-homekit/blob/master/include/homekit/characteristics.h#L585-L601

**Comment by ikalchev** [comment]
Will do later today, thanks. Will keep posted.

**Comment by ikalchev** [comment]
By the way, Valve and Faucet are already in HAP-python(sprinklers missing). Any idea if iOS 12 added those?

**Comment by cdce8p** [comment]
Totally missed that 😅 I always though they haven't been added yet, since they aren't listed in the HAP-Specifications. So I also haven't added them to Home Assistant yet.

I'm not 100% sure, but I think they have been added with 11.4. V12 should include Speakers and Remotes. Maybe you can check for those?

For sprinklers: Maybe they are just another kind of valve???

We should probably also update those then: 
https://github.com/ikalchev/HAP-python/blob/dev/pyhap/const.py#L18-L37

**Comment by ikalchev** [comment]
Speakers are there as well.

I downloaded HomeKit Simulator for Xcode 10 (from September this year) and re-ran the script. No new services or characteristics - only minor changes to which chars are optional/mandatory for which services, missing "units" values, etc. I also added the missing 2 categories as you suggester (based on the HAP-specification from Apple's site). This is already in dev, I will do a release to master tomorrow.

Let me know if something is still missing.

**Comment by cdce8p** [comment]
Thanks for updating!

Regarding `Speakers`: The last time I tried to use them, the service was meant for doorbells, but maybe that has changed to. I will check.

Additional categories: They might be unofficial, but I've also found those: [maximkulkin/esp-homekit](https://github.com/maximkulkin/esp-homekit/blob/51203ab6adff189bde03a468e460e9023c62f8c7/include/homekit/types.h#L60-L65). Do we want to add them as well?

Release: I noticed that the changelog needs to be updated. I'll submit a PR later to do so.

**Comment by ikalchev** [comment]
Damn I forgot the change log, need to get back to speed with this project. Thanks man!

The link you sent is for Accessory categories (that’s for the mDNS adverts), not services. I thought I had the latest HAP-spec, but I will re-download. Will add these as well. Thanks again

**Comment by ikalchev** [comment]
BTW I had another look at the project you sent - Here is a comment about the Speaker service:  

Defines that the accessory contains a speaker. This is mostly used for video doorbells and cameras and may not work standalone.

**Comment by cdce8p** [comment]
That was the last info I had as well regarding this topic, until I saw the HomeKit talk from WWDC 2018 and the slides this morning. There it lists `Speakers` and `Remotes` as new accessories. Check discord.

**Comment by cdce8p** [comment]
Just tested the `Speaker` service. It seems to be that way that it doesn't work on it's own.
