### ISSUE TITLE
Asyncio - SafeChildWatcher

### ISSUE THREAD

**Issue by cdce8p** [ikalchev/HAP-python#169]
https://github.com/ikalchev/HAP-python/blob/dev/pyhap/accessory_driver.py#L201-L203

`watcher.attach_loop` only works if the loop is in the main thread which isn't the case for Home Assistant. Thus this breaks it. As far as I understand the documentation for it, it isn't even necessary: https://docs.python.org/3/library/asyncio-policy.html#asyncio.SafeChildWatcher

**Comment by ikalchev** [comment]
https://docs.python.org/3/library/asyncio-subprocess.html#asyncio-subprocess-threads

> The child watcher must be instantiated in the main thread before executing subprocesses from other threads. Call the get_child_watcher() function in the main thread to instantiate the child watcher.

So either HAP or HA needs to set this before HAP can start subprocesses outside of the main tread.

What if HAP checks if we are in the main thread during startup and only then set that? Would that work for HA?

**Comment by ikalchev** [comment]
As discussed in discord, now adding a watcher only in the main thread. Let me know if this does not fit the bill.
