### ISSUE TITLE
Can`t share home in HomeKit app

### ISSUE THREAD

**Issue by dpylypen** [ikalchev/HAP-python#173]
When I give access to home with HomeKit app (on iPhone to iPhone for example) with bridge on HAP-python lib bride is not working with new device. How I can share access to bridges for several devices?

**Comment by cdce8p** [comment]
That isn't a `HAP-python` issue and should therefore be closed!

However you need to select `your Home` (top left corner in the Home App), then `Home Settings` -> `Home` -> `Invite...` for it to work. If that still doesn't work, a web search is probably better and should give you the solution. But to reiterate: This has nothing to do with `HAP-python`.

**Comment by ikalchev** [comment]
I agree with @cdce8p - other apple accounts that you invited should see your devices, given that they are in the same local network where HAP-python is running.
