### ISSUE TITLE
Support non-standard HAP services and characteristics

### ISSUE THREAD

**Issue by schinckel** [ikalchev/HAP-python#183]
Elgato Eve (for instance) has some non-Apple (and thus non-standard) services and characteristics. Some of these have been discussed at https://gist.github.com/simont77/3f4d4330fa55b83f8ca96388d9004e7d.

It would be really nice if there was some standard mechanism for creating a service/characteristic that is non-standard.

I think I'll be able to just create them using Service and Characteristic objects, but it might be nice to have the Loader handle that too.

**Comment by schinckel** [comment]
Actually, it should be possible to monkey-patch the result of `get_loader()` and add new definitions in there.

**Comment by ikalchev** [comment]
The `Loader` class should be able to do this - you just need a json file with chars and one with services. The format should be the same as the ones in the resources folder.

`my_loader = loader.Loader(“mychars.json”, “myservices.json”)`

Have you tried it?

**Comment by schinckel** [comment]
Oh neat. That looks like a much nicer solution than a dirty monkey-patch.
