### ISSUE TITLE
New Accessory Typs + Services

### ISSUE THREAD

**Issue by cdce8p** [ikalchev/HAP-python#185]
It seems their might have been new accessories added with iOS version 12.2 beta 1.
I recently saw a feature request to add a TV service and found this afterwards:
https://github.com/KhaosT/HAP-NodeJS/pull/638

I tried to download the current HAP specifications, but it seems they aren't available at the moment. At least I always get an error message. Maybe (Hopefully) they are being updated now.

**Comment by ikalchev** [comment]
Hey thanks for the info, I will try to add the new types soon.

**Comment by mprajsler** [comment]
Hi cdce8p, do you plan to implement TV service in HA once added in HAP? I.e. so my Philips TV with jointspace (in HA is mediaplayer) can be then exposed in Homekit as TV? This will be perfect.

**Comment by ikalchev** [comment]
I downloaded the latest HomeKitSimulator (fo Xcode 10.2 beta) and there is no TV there. So I see two options - I can try to manually copy from the HAP-NodeJS project or someone with a macOS mojave can send me the metadata from the HomeKitDaemon (I am still at high sierra as my HW is old).

**Comment by cdce8p** [comment]
I don't think a manual copy this is necessary. I would guess that Apple is updating their official specifications soon. There seems to be an event for late March, maybe then.

**Comment by ikalchev** [comment]
That would be the easiest and if there is no push for that feature, I would prefer it

**Comment by adrum** [comment]
Any update on this?

**Comment by ikalchev** [comment]
Unfortunately, the Apple HomeKit simulator (for Xcode 10.2 from march 25) still doesn't contain the metadata for these. I can try to manually add them as I mentioned earlier, but this would take a bit more time.
