### ISSUE TITLE
Implement Characteristic.set_value callback toggle.

### ISSUE THREAD

**Issue by tagdara** [ikalchev/HAP-python#19]
I have a large framework for a home automation system which in many ways is a bridge of bridges, acting as an overall compatibility and abstraction layer across multiple systems.  

- I can set the values of the lights for Homekit directly from my code using service.characteristic.set_value and this works no problem.
- I need to be notified about lights change requests from a Homekit user so that I can reflect that on the actual device.  Added a setter_callback which pushes the requested change to my code (which then applies it to the physical light) and this works no problem

However with both of these components in place, my code sets the value of the light, which triggers the callback, which calls my code, which updates the value of the light, which triggers the callback (repeat forever).

Is there a way for me to differentiate so that the callback is only triggered when a user makes a change and not when the device is updated from my code?

**Comment by ikalchev** [comment]
Hi! This is an interesting problem indeed. I can offer the following workaround (discussion for a future non-workaround to follow):

To avoid triggering the callback, your code can do the following:
```python
c = the_characteristic
c.value = 42  # set raw value
c.notify()  # notify iOS clients
```
The drawback of the above, besides the decoupling of the two operations, is that the check that the new value is in the set of valid values for this type of char. is not performed (it is done in `set_value`). If you want to implement that check, do:
```python
c = the_characteristic
assert new_value in c.properties["ValidValues"]
```

I will give more thought on your problem and may add an arg to set_value, which controls whether the callback is called. Then, set this to True in case a user update comes in.

How does the above sound? Thoughts and suggestions are welcome.

Best regards,
Ivan

**Comment by tagdara** [comment]
The workaround you describe is exactly what I'm doing right now to solve this.  I wasn't sure if there was a cleaner way, but it makes sense.

I also agree that perhaps just having a callback toggle similar to the notify toggle that defaults to true would be the simple solution.

**Comment by ikalchev** [comment]
The more I think about it the more it makes sense to add this. Alternatively, there could be a dedicated method for handling user-triggered updates.

I think the toggle is better. In any case, I will try to push either in a few days. Will keep you posted.

**Comment by ikalchev** [comment]
@tagdara By the way, can you explain the use case again? Why is `set_value` called in your `setter_callback`, when the value is set just prior to the callback being called?

**Comment by ikalchev** [comment]
Thanks for the thorough explanation. No need to share the code.

What `set_value` does is to:
1. Check if the new value is in the valid values (if any). Raise if not.
2. Do `self.value = value   <<<`
3. If there is a callback, call it, passing the new value.
4. If should_notify, send update to clients.

In other words, in the callback the value is already set to the characteristic, i.e. no need to do `set_value` there. I think this solves your problem, right?

If you want different behaviour of Characteristic, you can create a call the loader with a different type to instantiate as a Characteristic. See this https://github.com/ikalchev/HAP-python/blob/master/pyhap/loader.py#L32. This ideally should be passed in the constructor of the CharacteristicLoader - this is a future improvement on my side.

**Comment by ikalchev** [comment]
@tagdara any comments on the above?

**Comment by ikalchev** [comment]
My previous comments explain why a call to `set_value` inside the callback is not necessary. Please reopen if you do not agree, so that we can discuss it further :)

**Comment by ikalchev** [comment]
Okay I get the use case for the callback toggle, reopening this. FYI @schinckel
