### ISSUE TITLE
Television accessory, InputSource characteristic caused bridge pairing failure

### ISSUE THREAD

**Issue by quadcube** [ikalchev/HAP-python#195]
Tried implementing TV accessory, which basically worked until I added the SourceInput service. The TV accessory implemented on a bridge, which initial pairing process showed pairing was successful on the HAP-python side and then both iOS and HAP-python showed pairing failed/unable to pair.

Here's a snippet of the TV accessory with SourceInput
`
class MacMini(Accessory):

    category = CATEGORY_TELEVISION
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        serv_macmini = self.add_preload_service('Television', chars=['Active', 'ActiveIdentifier', 'ConfiguredName', 'SleepDiscoveryMode', 'CurrentMediaState', 'TargetMediaState', 'RemoteKey'])
        serv_speaker = self.add_preload_service('TelevisionSpeaker', chars=['Mute', 'VolumeSelector'])
        #serv_inputsource = self.add_preload_service('InputSource', chars=['ConfiguredName', 'InputSourceType', 'IsConfigured', 'CurrentVisibilityState'])
        
        self.active = serv_macmini.configure_char('Active', setter_callback=self.set_active)
        self.activeidentifier = serv_macmini.configure_char('ActiveIdentifier', setter_callback=self.set_activeidentifier)
        self.configuredname_macmini = serv_macmini.configure_char('ConfiguredName')
        self.sleepdiscoverymode = serv_macmini.configure_char('SleepDiscoveryMode', setter_callback=self.set_sleepdiscoverymode)
        self.targetmediastate = serv_macmini.configure_char('TargetMediaState', setter_callback=self.set_targetmediastate)
        self.remotekey = serv_macmini.configure_char('RemoteKey', setter_callback=self.set_remotekey)
        
        self.char_mute = serv_speaker.configure_char('Mute', setter_callback=self.set_mute)
        self.char_volume = serv_speaker.configure_char('VolumeSelector', setter_callback=self.set_volume)
    
        self.configuredname_inputsource = serv_inputsource.configure_char('ConfiguredName')
        self.inputsourcetype = serv_inputsource.configure_char('InputSourceType', setter_callback=self.set_inputsourcetype)
        self.isconfigured = serv_inputsource.configure_char('IsConfigured')
        self.currentvisibilitystate = serv_inputsource.configure_char('CurrentVisibilityState')
        
        self.configuredname_macmini.set_value('Mac mini')
        self.configuredname_inputsource.set_value('Thunderbolt 3')
        self.sleepdiscoverymode.set_value(1)
        self.inputsourcetype.set_value(3)
        self.isconfigured.set_value(0)
        self.currentvisibilitystate.set_value(0)
    
    @Accessory.run_at_interval(30)
    def run(self): # We can't just use .set_value(state), because that will trigger our listener
        state = get_display_state()
        if self.active.value != state:
            self.active.value = state
        self.active.notify()
    
    def set_active(self, value):
        if get_display_state() != value:
            set_display_state(value)

    def set_activeidentifier(self, value):
        print("Active Identifier: %s", value)

    def set_sleepdiscoverymode(self, value):
        print("Sleep Discovery Mode: %s", value)

    def set_targetmediastate(self, value):
        print("Target Media State: %s", value)
    
    def set_remotekey(self, value):
        print("Remote Key: %s", value)
    
    def set_inputsourcetype(self, value):
        print("Input Source Type: %s", value)
    
    def set_mute(self, value):
        print("Mute: %s", value)

    def set_volume(self, value):
        print("Volume: %s", value)
`

**Comment by quadcube** [comment]
Snapshot from iPhone and HAP-Python pairing process

![IMG_5298](https://user-images.githubusercontent.com/13719009/59159077-740fd900-8aff-11e9-90ed-a41d93e55795.PNG)

[hap_server] Got connection with ('192.168.88.225', 53569).
[hap_server] 192.168.88.225 - "POST /pair-setup HTTP/1.1" 200 -
[hap_server] 192.168.88.225 - "POST /pair-setup HTTP/1.1" 200 -
[accessory_driver] Paired with 688b23cb-3b83-45fd-82ec-0660e615c5a5.
[hap_server] 192.168.88.225 - "POST /pair-setup HTTP/1.1" 200 -
[hap_server] Got connection with ('192.168.88.225', 53570).
[hap_server] 192.168.88.225 - "POST /pair-verify HTTP/1.1" 200 -
[hap_server] 192.168.88.225 - "POST /pair-verify HTTP/1.1" 200 -
[hap_server] 192.168.88.225 - "GET /accessories HTTP/1.1" 200 -
[accessory_driver] Unpairing client 688b23cb-3b83-45fd-82ec-0660e615c5a5.

**Comment by maximkulkin** [comment]
Fixed by #202 

The problem was with incorrect specification for valid values of CurrentVisibilityState and lack of "valid-values" reporting in characteristics json.

**Comment by quadcube** [comment]
Tested your fix, it works! Thanks a lot!
