### ISSUE TITLE
HTTP server must be HTTP/1.1

### ISSUE THREAD

**Issue by a3135134** [ikalchev/HAP-python#197]
According to HAP specification 5.2.4, HTTP server must be HTTP/1.1. Now it's 1.0.

If the controller doesn't maintain a persistent connection, the pair verify progress will raise an error. And HTTP 1.0 doesn't require a persistent connection by default.

I just added the code
self.protocol_version = "HTTP/1.1" 
in __init__() function of  class HAPServerHandler in "/pyhap/hap_server.py". And it works.

**Comment by schinckel** [comment]
This seems to have fixed the issues I've noticed recently too, where my HAP-python bridge would drop-off fairly frequently.

**Comment by schinckel** [comment]
...may have spoken too soon... :(

**Comment by bdraco** [comment]
@schinckel  Does https://github.com/bdraco/HAP-python/commit/fbabe83c15f08c01654f5acac2e9e53a7aeeae05 solve this for you?

**Comment by schinckel** [comment]
I’m not sure that the problems I was seeing were application-related: I think it was a configuration issue, where reflected advertisements caused the zeroconf library to stop advertising.
