### ISSUE TITLE
iPhone does not reconnect with bridge

### ISSUE THREAD

**Issue by sander-vd** [ikalchev/HAP-python#221]
After disabling / enabling wifi on the Iphone, the Home app does not automatically reconnects to the bridge, no error and RPI is still responsive. 

Status in app is: no response

Restarting HAP fixes the issue

**Comment by bdraco** [comment]
Should be solved in 2.7.0+

**Comment by ikalchev** [comment]
Reopen if the issue persists in 2.7.0
