### ISSUE TITLE
How do i make an accessory that isn't a temperature sensor?

### ISSUE THREAD

**Issue by shayypy** [ikalchev/HAP-python#223]
There are no examples in the documentation ("to be filled out"), so I feel as though I'm limited to the examples provided on PyPI and github. Is there something I should be using to see what I can make the category? As per a provided example, `CATEGORY_SENSOR`. 

The provided example works fine, but as stated I don't know what else im able to make. Ideally I want to just have a number or a %. Or even a string, that'd be neat. 

Thanks for any help.

**Comment by baxcat** [comment]
While i'm here, how do you something where it runs a function upon clicking a button in the Home app? I haven't delved too far into this library, so sorry if this is all very obvious.

**Comment by Hoefnix** [comment]
Although it is interesting to reverse engineer the library I could use some examples as well.

**Comment by ikalchev** [comment]
Here are some example accessories: https://github.com/ikalchev/HAP-python/tree/dev/accessories

Also https://github.com/ikalchev/pyhap-maxcube

Sorry for the missing docs, will try to do better when I have the time.
