### ISSUE TITLE
Generate QR Code (and X-HM:// url)

### ISSUE THREAD

**Issue by schinckel** [ikalchev/HAP-python#24]
A nice feature about Homebridge/hap-nodejs is that you can scan a QR code in a terminal window.

I've had a quick look at the code for generating it, and if I can port it to Python I'll create a PR.

**Comment by schinckel** [comment]
So the URL is made up of two parts: the first is made from the `pincode` and the `category` of the accessory - the other part is (at least in the case of `homebridge`) appears to come from the `setupID`, which I believe is used (along with something else) to generate the `sh` field of the bonjour advertisement.

I'm not sure exactly how to get this part, just yet.

**Comment by ikalchev** [comment]
I looked at the js code, here is what I found:

1. The `sh` field seems to be new, and HAP-python is missing it. I can try to add this in a few days.
2. The above is generated using the username (i.e. mac) and setupID of the Accessory. I couldn't find what the setup ID is...

Here are all the ingredients in HAP-python.
```python
acc = Accessory(...)
pin = acc.pincode
cat = acc.category
mac = acc.mac  # this is acc.username in HAP-Nodejs
setupID = ??
```

If you can find any info on the setup ID, that will be great. Will keep posted.

**Comment by schinckel** [comment]
I believe it’s “just a value”, that is 4 alpha-numeric chars. In the case of hap-nodejs it appears to be a constant value, unless it’s overridden. I think if it’s not supplied we can create a value and then persist that. 

For initial dev I’ll try a fixed string.

**Comment by ikalchev** [comment]
Sounds good. Will you be working on the QR only or will you try to add the `sh` field as well? Cause I can start with the `sh`.

**Comment by schinckel** [comment]
I’ve got the QR code stuff working: it uses a couple of dependencies, but it’s fairly simple. It’s just the setupID is appended to the url.

**Comment by ikalchev** [comment]
Awesome. Waiting for a PR :)

**Comment by schinckel** [comment]
Bah, I had it working - then I must have mucked something up when extracting it out of my code and into the `HAP-python` code.

**Comment by jslay88** [comment]
Did a bit of the initial ground work. I don't have access to Apple Documentation, so I built what I could from this snippet. 
https://github.com/nfarina/homebridge/issues/1588#issuecomment-341158722

**Comment by schinckel** [comment]
Okay, I think it's just the QR code that is problematic: I'm generating a url which is identical to `homebridge`.

**Comment by jslay88** [comment]
I got it just now. :)

**Comment by schinckel** [comment]
Turns out I was not removing the trailing `\n` on the setup hash in the advertisement - that was why it was not working.

**Comment by ikalchev** [comment]
Hi all, 

Great work from both! I have some just minor comments, which are on the review. I really have no preference on which change goes in, so could you please discuss this between you? Also I do very much like the setup_message from pull #31.

As @schinckel did, I would prefer two changes - one for QR/uri and another for dynamic pincode.

**Comment by jslay88** [comment]
honestly, doesn't matter to me. I was just trying to get my garage door on Siri :) and had a good JS example to work from, since I don't have access to Apple Documentation. 

I was more just trying to learn the whole contributing process more than anything by putting it into practice. I'd have no feelings hurt if mine was not taken.

**Comment by ikalchev** [comment]
Okay so how about this: I am ready to merge @schinckel #34 right away, then @jslay88 can reuse setup_id/pincode logic in the QR/URI change. How does that sound?

**Comment by jslay88** [comment]
that works for me, I'll use the conflict report to correct my PR

**Comment by ikalchev** [comment]
Done, go ahead with the conflicts @jslay88.

**Comment by ikalchev** [comment]
Thanks both. I will dump the version and will push this to pypi by end of today.

I will be away for a few hours now.

**Comment by ikalchev** [comment]
FYI this doesn't work for me. @jslay88 does it work for you?

**Comment by jslay88** [comment]
Nope. Not getting the 00 buffer on the front. Something isn't right after the merge. Let me dig for a moment.

**Comment by jslay88** [comment]
#38

**Comment by ikalchev** [comment]
Works like a charm now.
