### ISSUE TITLE
Unable to encode TLV value for camera

### ISSUE THREAD

**Issue by jdsnape** [ikalchev/HAP-python#242]
When trying to create a camera I'm getting this exception:

```
[hap_server] Exception in set_characteristics: object of type 'int' has no len()
Traceback (most recent call last):
  File "/home/homekit/camera_test/venv/lib/python3.7/site-packages/pyhap/hap_server.py", line 559, in handle_set_characteristics
    self.client_address)
  File "/home/homekit/camera_test/venv/lib/python3.7/site-packages/pyhap/accessory_driver.py", line 660, in set_characteristics
    char.client_update_value(cq[HAP_REPR_VALUE], client_addr)
  File "/home/homekit/camera_test/venv/lib/python3.7/site-packages/pyhap/characteristic.py", line 215, in client_update_value
    self.setter_callback(value)
  File "/home/homekit/camera_test/venv/lib/python3.7/site-packages/pyhap/camera.py", line 694, in set_endpoints
    to_base64=True)
  File "/home/homekit/camera_test/venv/lib/python3.7/site-packages/pyhap/tlv.py", line 27, in encode
    total_length = len(data)
```

I think I can see how this has happened in camera.py as tlv.encode is (I think) expecting to receive bytes, but it's being passed video_ssrc/audo_ssrc which are integers.

```
       video_ssrc = int.from_bytes(os.urandom(3), byteorder="big")
        audio_ssrc = int.from_bytes(os.urandom(3), byteorder="big")

<snip>
        response_tlv = tlv.encode(
            SETUP_TYPES['SESSION_ID'], session_id.bytes,
            SETUP_TYPES['STATUS'], SETUP_STATUS['SUCCESS'],
            SETUP_TYPES['ADDRESS'], res_address_tlv,
            SETUP_TYPES['VIDEO_SRTP_PARAM'], video_srtp_tlv,
            SETUP_TYPES['AUDIO_SRTP_PARAM'], audio_srtp_tlv,
            SETUP_TYPES['VIDEO_SSRC'], video_ssrc,
            SETUP_TYPES['AUDIO_SSRC'], audio_ssrc,
            to_base64=True)
```

This used to work though so I'm a bit confused about what has changed! I'm using python 3.7.5 and HAP-python==2.8.2

**Comment by jdsnape** [comment]
It looks like the change was introduced in commit ce394c03d1c967c4a6a01f32f7a48fbc262b4606 as part of the #231 fixes. I was using 2.7.0 when it worked before. I'm not sure whether I'm doing something wrong though as this would seem to always fail?

I changed the tlv.encode command to use struct.pack to convert to bytes and seems to work OK. Can do a pull req but wanted to check whether I'd missed something first...

```
        response_tlv = tlv.encode(
            SETUP_TYPES['SESSION_ID'], session_id.bytes,
            SETUP_TYPES['STATUS'], SETUP_STATUS['SUCCESS'],
            SETUP_TYPES['ADDRESS'], res_address_tlv,
            SETUP_TYPES['VIDEO_SRTP_PARAM'], video_srtp_tlv,
            SETUP_TYPES['AUDIO_SRTP_PARAM'], audio_srtp_tlv,
            SETUP_TYPES['VIDEO_SSRC'], struct.pack('<I', video_ssrc),
            SETUP_TYPES['AUDIO_SSRC'], struct.pack('<I', audio_ssrc),
            to_base64=True)
```

**Comment by bdraco** [comment]
@xdissent can you take a look?

**Comment by bdraco** [comment]
@jdsnape Your fix looks right to me.

**Comment by bdraco** [comment]
@jdsnape Does the test pass now?

**Comment by jdsnape** [comment]
@bdraco It’s been running for about 24hours  without an issue after making that change. 

I’m a bit surprised though as I can’t see how a camera would ever work as it is in the release?

**Comment by bdraco** [comment]
> @bdraco It’s been running for about 24hours  without an issue after making that change. 
> 
> 
> 
> I’m a bit surprised though as I can’t see how a camera would ever work as it is in the release?

Good news!  Can you put in a PR to fix this?

**Comment by jdsnape** [comment]
@bdraco okydoke - done in #243

**Comment by xdissent** [comment]
Looks good to me! Thanks y'all
