### ISSUE TITLE
self.broker.publish -> self.broker == None

### ISSUE THREAD

**Issue by helmsman35** [ikalchev/HAP-python#25]
Hi,

I am writing an adapter for HomeAssistant and I have been able to add a bridge, with a temperature and humidity sensors. Pairing goes fine but If I get an updated value from homeassistant I get an Error:

`Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/HomeKit.py", line 105, in update_value
    self.hum_char.set_value(float(new_state.state))
  File "/opt/homeassistant/lib/python3.5/site-packages/pyhap/characteristic.py", line 141, in set_value
    self.notify()
  File "/opt/homeassistant/lib/python3.5/site-packages/pyhap/characteristic.py", line 174, in notify
    self.broker.publish(data, self)
  File "/opt/homeassistant/lib/python3.5/site-packages/pyhap/accessory.py", line 328, in publish
    self.broker.publish(acc_data)
AttributeError: 'NoneType' object has no attribute 'publish'`

update_value is a class method of (in this case HumiditySensor, same for TemperatureSensor) which is called by HomeAssistant with the updated value.

my code for Humidity Sensor:

```
class HumiditySensor(Accessory):
    category = Category.SENSOR
    
    def __init__(self, *args, **kwargs):
        super(HumiditySensor, self).__init__(*args, **kwargs)
        self.hum_char = self.get_service("HumiditySensor").get_characteristic("CurrentRelativeHumidity")
#        self.hum_char.setter_callback = self.humidity_changed

#    def humidity_changed(self, value):
#        _LOGGER.error("Humidity Changed : " +str(value))


    def _set_services(self):
        super(HumiditySensor, self)._set_services()
        hum_sensor_service = loader.get_serv_loader().get("HumiditySensor")
        self.add_service(hum_sensor_service)

    def update_value(self,entity_id, old_state, new_state):
        self.hum_char.set_value(float(new_state.state))

bridge = False # points to the bridge object after init

def setup(hass,config):
   global bridge #Not sure If I need this...
    T = TemperatureSensor("Temperatuur ")
    H = HumiditySensor("Relatieve Luchtvochtigheid")
    _LOGGER.info("HomeKit bridge started ...")
    _LOGGER.info("display_name: "+config[DOMAIN]["display_name"])
    bridge = Bridge(display_name = config[DOMAIN]["display_name"],pincode=b"123-45-678")
    bridge.add_accessory(T)
    bridge.add_accessory(H)
    if os.path.exists("accessory.pickle"):
        with open("accessory.pickle","rb") as f:
            acc=pickle.load(f)
    else:
        acc=bridge
    driver = AccessoryDriver(acc, 51826, address="10.3.3.40")
    driver.start()

    def handle_homeassistant_stop(event):
        driver.stop()

    hass.bus.listen('homeasststant_stop', handle_homeassistant_stop)
    track_state_change(hass, "sensor.temperatuur_woonkamer_bmp", T.update_value)
    track_state_change(hass, "sensor.relatieve_luchtvochtigheid", H.update_value)

```
setup is called by HomeAssistant at startup

I have to set the tcpip address as I have a dual homed server. and driver.stop() is called when HomeAssistant is about to exit/stop and the last two lines are to track the update value events.

I'm puzzled where this error comes from, I must have forgotten something.

Any help on how to find out what is wrong would be highly appreciated!

Kind regards,

Martijn

**Comment by helmsman35** [comment]
I just found out that if I remove accessories.pickle, restart HomeAssistant, repair everything works as expected, once I restart HomeAssistant (and accessories.pickle is loaded) I get the error above on status updates calling update_value, I guess update_value is pickled and restored wrong?

I tried to rename update_value to _update_value with no success...

**Comment by helmsman35** [comment]
Ok, My mistake!

I initialised the Accessories and bridge before I checked for the pickle load...

New code:

```
def setup(hass, config):
    _LOGGER.info("HomeKit bridge started ...")
    _LOGGER.info("display_name: "+config[DOMAIN]["display_name"])
    _LOGGER.info("pincode: "+config[DOMAIN]["pincode"])
    #httpbridge.add_accessory(W1)
    #httpbridge.add_accessory(W2)
    if os.path.exists("accessory.pickle"):
        with open("accessory.pickle","rb") as f:
            acc=pickle.load(f)
    else:
        T = TemperatureSensor("Temperatuur ")
        H = HumiditySensor("Relatieve Luchtvochtigheid")
        bridge = Bridge(display_name = config[DOMAIN]["display_name"],pincode=b"123-45-678")
        bridge.add_accessory(T)
        bridge.add_accessory(H)
        acc=bridge

    driver = AccessoryDriver(acc, 51826, address="10.3.3.40")
    driver.start()

    def handle_homeassistant_stop(event):
        driver.stop()

    hass.bus.listen('homeasststant_stop', handle_homeassistant_stop)

```

and I moved the configuration of the event handling to the __init__ of the Sensor objects, Now everything seems working OK!

Martijn

**Comment by ikalchev** [comment]
I am happy you got it working. The error you see was because the accessory was started before it is added to an AccessoryDriver. To be honest, I should maybe change the code to do nothing in this case and not crash the world.

Best,
Ivan

**Comment by helmsman35** [comment]
I have some more issues right now, as after the pickle load, the __init__ of the accessory seems not to be called (I added a value before the accessory in the accessory.__init__), I must find a way to restore the event catching. As you can see, I do not run any code in accessory.Run. That might be a solution but I need a reference to the object in HomeAssistant to start the event handling. I foresee an issue with the circular events when I handle user/Siri changes. The solution is in another thread (issue), so I can use that. I will wait for the changes you make to the pickle and see how to fit my plans in that situation. 

I see where this is coming from, as your intentions where a stand-alone daemon and I need to integrate into the model of HomeAssistant, part of the fun :)

**Comment by ikalchev** [comment]
I want to make it easy for others to plug in, like in your case. So your input is really valuable here.

My change is mostly done, I am just writing a small piece of code that will take the pickle and create the new state representation (which is a json file with 1/10 the size). This is so that old clients can upgrade seamlessly.

If I outline my design here, could you share some thoughts and whether it would work for you?

**Comment by helmsman35** [comment]
Sure! I was about to implement exactly what you did, until I googled for HomeKit python once again.
The homeassistant cumminity is really interested in my work, as the only way is nodejs/homebridge/homeassistant-homebridge. And nodejs is exactly what I replace with homeassistant. I’m no fan of using JavaScript for home automation stuff. People tend to grab what is available. Lots of people use homeassistant on a rPi where homebridge uses 10%cpu on its own....

I am off to work, I might respond but do not have access to my code from there

**Comment by ikalchev** [comment]
Not being a fan of JS for home automation too is why I made HAP-python :)

Ok, I will start with a short background to be on the same page.

The iOS clients remember certain properties of the Accessories they pair with, such as MAC address, the Accessory public key, etc. This means that on each restart of the Accessory, these same values need to be available, otherwise iOS clients will not be able to "recognise" the Accessory they already paired with. 

Currently, the whole Accessory object hierarchy is pickled, which is easily broken between python versions, HAP-python updates and so on. Additionally, it takes an overkill amount of space.

# The change

The change in question addresses all these problems by specifying an `AccessoryEncoder` interface, which consists of two methods - `persist` and `load_into`. `persist` takes an accessory and extracts:
- Its MAC address
- Its public and private keys
- The UUID and public key of all paired clients
- the current config version (this is how HAP tracks accessory config changes)

and writes all these in a given file using json.

The `load_into` takes a file and an Accessory, reads all the above properties from the file and sets them into the given Accessory.

The change adds a default encoder parameter to the AccessoryDriver init, which it uses to persist the state after certain events. It also checks if the given "persist_file" exists and loads the state for you (if it does not exist it will create it and dump the Accessory state in it, i.e. calls `AccessoryEncoder.persist`).

So the flow from a user point of view becomes much more intuitive:
```python
acc = create_accessory()
driver = AccessoryDriver(acc, port=12345)  # persist_file="accessory.state" by default
driver.start()
# The above automatically checks for available state in the persist file.
# Note that you need to create the accessory on every (re)start.
# But this is fine, we distinguish state from the actual "logic".
# Also, your init gets called every time, which is a good thing.
```

Disadvantages I can think of are:
- Characteristic values are not persist between restarts - this I think is fine, because an accessory shows the current state, so some logic needs to set that anyway.

As I said, I have only the backwards-compatibility to take care of and expect to submit today. Thoughts are very welcome :) Also, I will be happy to help with the Home Assistant integration, should you need anything.

**Comment by helmsman35** [comment]
Cool, I agree with the solution.

The disadvantage is really non existent as -on a restart of homeassistant- the states will update anyway.

I am running your lib as a Bridge, which is started as Homeassistant Is started. Most of the values are "Unkown" at start. once the sensors etc are initialised the events indicating a value/state change would set the actual values.

HomeKit.py (using HAP-python) is a Homeassistant component.
Are you familiar with Homeassistant? 

I did do a fair bit of customising homebridge to accommodate my Receiver, Television. By setting Scenes in homekit, I was able of asking Siri to watch a certain TV channel, listen to a certain radio station setting all inputs (my receiver get the TV sound to my speakers) etc.

I created my own Accessories and found that the "string" type was not supported in homebridge so I suggested an change. I am familiar with the inner workings of homekit. My current project was announced in the Homeassistant dev chat channel and I got hundreds of responses from people who want to get rid of nodejs/homebridge for homekit/Siri integration.....

I am aiming for a glue between HAP-python and Homeassistant which does not need any programming and which should be configurable within the Homeassistant configuration files. Even for custom accessories. 

I know my way around python as I use that professionally since 1999 (or 1998, do not remember) and I have made anything from antenna positioning (satellites) up to a python to javascript compiler (I hate javascript that much!) or a fully automated HDD/SDD wipe and quality check rig capable of concurrently handling > 10,000 HDD's (basically there is no limit)

I might take a part of the afternoon off to work on this, I'll keep an eye on git.

**Comment by ikalchev** [comment]
> Are you familiar with Homeassistant?

Unfortunately, I am not, but it sounds like fun, I will take a look at it.

> My current project was announced in the Homeassistant dev chat channel and I got hundreds of responses from people who want to get rid of nodejs/homebridge for homekit/Siri integration.....

Sounds awesome! Let me know how can I help make the glue between HAP-python and Home Assistant. I was thinking of adding configuration files in which you just say "I want these and these Accessories with these and these characteristics", but I am not sure this will cover enough use cases. I was thinking about a hybrid approach - config files and some programming on top of them. Is this the workflow in Home Assistant?

> I might take a part of the afternoon off to work on this, I'll keep an eye on git.

I will tag you when I close the issue.

**Comment by helmsman35** [comment]
OK, I'm back home and "up and running", is there any way we can discuss stuff on Skype, slack, discord or whatever? I have some questions on how to some things. and I do not want to create an issue as the issue is mine, not with this code

**Comment by helmsman35** [comment]
OK for now I have a temporary solution

acc=bridge or acc=pickle.load depending on first start or a restart.

```
    driver = AccessoryDriver(acc, 51826, address="10.3.3.40")
    for item in acc.accessories:
        acc.accessories[item].set_event_listeners()

```

every Accessory most have:

```
    def set_event_listeners(self):
        track_state_change(homeassistant, self.entity_id, self.update_value)

```

Now when a state changes the Accessory.update_value is called by Homeassistant,
even after the restart.... this will do until the new pickle alternative is implemented.

**Comment by ikalchev** [comment]
My Skype is "imortalitymen" (yeah I know). Ping me when you write that down, I would like to delete this :D. The change is in btw (and in pypi), I have tagged you in the corresponding issue.
