### ISSUE TITLE
Cleaning connection for no apparent reason, resulting in No Response

### ISSUE THREAD

**Issue by SebasT87** [ikalchev/HAP-python#257]
I have been breaking my head around an issue where my non-HomeKit devices published through Home Assistant are not responding every couple of minutes. My true-HomeKit devices are no problem though.

The problem starts when the connection gets cleaned (for no apparant reason), see log

> 2020-05-26 08:01:01 DEBUG (Thread-17) [pyhap.accessory_driver] Subscribed client ('192.168.1.25', 49795) to topic 2225605144.9
> 2020-05-26 08:01:01 DEBUG (Thread-17) [pyhap.accessory_driver] Subscribed client ('192.168.1.25', 49795) to topic 2225605144.10
> 2020-05-26 08:01:01 INFO (Thread-17) [pyhap.hap_server] 192.168.1.25 - "PUT /characteristics HTTP/1.1" 204 -
> 2020-05-26 08:03:49 DEBUG (Thread-17) [pyhap.hap_server] Cleaning connection to ('192.168.1.25', 49795)

After this nothing gets logged for some time (somtimes up to a couple of minutes) and the devices are not responding. Then all of a sudden it connects and the devices start responding again. After a couple of minutes this loop starts over.

> 2020-05-26 08:09:07 INFO (Thread-5) [pyhap.hap_server] Got connection with ('192.168.1.25', 49796).
> 2020-05-26 08:09:07 DEBUG (Thread-18) [pyhap.hap_server] Request POST from address '('192.168.1.25', 49796)' for path '/pair-verify'.
> 2020-05-26 08:09:07 DEBUG (Thread-18) [pyhap.hap_server] Pair verify [1/2].
> 2020-05-26 08:09:07 INFO (Thread-18) [pyhap.hap_server] 192.168.1.25 - "POST /pair-verify HTTP/1.1" 200 -
> 2020-05-26 08:09:07 DEBUG (Thread-18) [pyhap.hap_server] Request POST from address '('192.168.1.25', 49796)' for path '/pair-verify'.
> 2020-05-26 08:09:07 DEBUG (Thread-18) [pyhap.hap_server] Pair verify [2/2]
> 2020-05-26 08:09:07 DEBUG (Thread-18) [pyhap.hap_server] Pair verify with client '('192.168.1.25', 49796)' completed. Switching to encrypted transport.
> 2020-05-26 08:09:07 INFO (Thread-18) [pyhap.hap_server] 192.168.1.25 - "POST /pair-verify HTTP/1.1" 200 -

What might be causing it to clean the connections and is this expected behaviour?

**Comment by bdraco** [comment]
Can you try with the latest code in the repo?

**Comment by bdraco** [comment]
#253 May have fixed this (it did for me)

**Comment by SebasT87** [comment]
Thanks for your response!
I can certainly give this a try. Do you have some short directions on how to pull the latest code?
I’m an IT guy but not much experience in this field. So only short directions should lead me in the right direction. Fyi .. I’m running home assistant core appliance on VMware 
Thanks again!

**Comment by bdraco** [comment]
In your home assistant install modify `manifest.json` so `HAP-python` doesn't get reinstalled

```
diff --git a/homeassistant/components/homekit/manifest.json b/homeassistant/components/homekit/manifest.json
index 8f7382b5d8..0971b39174 100644
--- a/homeassistant/components/homekit/manifest.json
+++ b/homeassistant/components/homekit/manifest.json
@@ -2,7 +2,7 @@
   "domain": "homekit",
   "name": "HomeKit",
   "documentation": "https://www.home-assistant.io/integrations/homekit",
-  "requirements": ["HAP-python==2.8.4","fnvhash==0.1.0","PyQRCode==1.2.1","base36==0.1.1","PyTurboJPEG==1.4.0"],
+  "requirements": ["fnvhash==0.1.0","PyQRCode==1.2.1","base36==0.1.1","PyTurboJPEG==1.4.0"],
   "dependencies": ["http", "camera", "ffmpeg"],
   "after_dependencies": ["logbook", "zeroconf"],
   "codeowners": ["@bdraco"],
```

In your home assistant environment run the following
```
git clone https://github.com/ikalchev/HAP-python
cd HAP-python
pip3 install --upgrade .
```


You may also want to turn on debugging for `pyhap` and `homekit` in your `configuration.yaml`:
```
logger:
  default: info
  logs:
     homeassistant.components.homekit: debug
     pyhap: debug
```

Restart Home Assistant

**Comment by SebasT87** [comment]
Thanks, this should give me enough guidance 👍🏻
I will give it a try tonight

**Comment by SebasT87** [comment]
`pip3 install --upgrade` .didn't work. 
My guess is i needed to run this `pip3 install --upgrade ./` correct?

**Comment by bdraco** [comment]
`pip3 install --upgrade .` or `pip3 install --upgrade ./` should both work

**Comment by SebasT87** [comment]
Haha totally missed the dot in your instructions.. your right both should do the trick. Same on me haha

**Comment by SebasT87** [comment]
It was worth the shot but unfortunately it didn’t seem to solve the problem.
Any ideas to troubleshoot this further?

Thanks!

**Comment by bdraco** [comment]
> It was worth the shot but unfortunately it didn’t seem to solve the problem.
> Any ideas to troubleshoot this further?
> 
> Thanks!

Try rebooting the device after the changes are in place to make sure things are back in sync.

**Comment by SebasT87** [comment]
Assuming you mean rebooting my iPhone/iPad? Tried that but unfortunatly no improvement

**Comment by bdraco** [comment]
Is it still dropping after the `Switching to encrypted transport.`?

**Comment by bdraco** [comment]
Reverified for me.  Downgrading all the unexpected `Cleaning` comes back.  Upgrading to `upstream/dev` and the problem goes away.

Can you get a tcpdump/wireshare/pcap of the data?

**Comment by bdraco** [comment]
Also, did you try unpairing and repairing after the upgrade ?

**Comment by bdraco** [comment]
Also looks like we are closing connections too soon because the timeout is too low

```
2020-05-26 19:41:52 INFO (Thread-147) [pyhap.hap_server] 192.168.213.90 - "PUT /characteristics HTTP/1.1" 204 -
2020-05-26 19:41:52 DEBUG (Thread-147) [pyhap.hap_server] sendall: b'HTTP/1.1 204 No Content\r\n\r\n'
2020-05-26 19:46:52 INFO (Thread-147) [pyhap.hap_server] 192.168.213.90 - Request timed out: timeout('timed out')
2020-05-26 19:46:52 DEBUG (Thread-147) [pyhap.hap_server] Cleaning connection to ('192.168.213.90', 64831)
```

**Comment by SebasT87** [comment]
> 
> 
> It should drop when the device goes to sleep or finishes all the `PUT` subscribes.
> 
> Is it still dropping after the `Switching to encrypted transport.`?

If it should drop when device goes to sleep then this is probably expected behaviour becasue that's what happens at this point. But i have also seen it drop with the device fully active and refreshing the camera still every 10 secs.
But the problems is that it won't reconnect (or atleast takes for ages) when the device is active again after the connection is cleaned. FYI the device also cannot find hap.tcp with MDNS anymore when this is the case. So maybe we're looking at a problem with zeroconf?

**Comment by bdraco** [comment]
I recently fixed an issue where `zeroconf` announcements would go away after the initial announcement in `0.26.2`

Can you try upgrading `zeroconf` by changing the version 
 in `homeassistant/components/zeroconf/manifest.json` to `0.26.2` and restarting

**Comment by SebasT87** [comment]
Also seeing these from time to time

```
2020-05-26 22:14:24 DEBUG (Thread-4) [pyhap.accessory_driver] Sending event to client: ('192.168.1.108', 49191)
2020-05-26 22:14:24 DEBUG (Thread-4) [pyhap.hap_server] No socket for ('192.168.1.108', 49191)
2020-05-26 22:14:24 DEBUG (Thread-4) [pyhap.accessory_driver] Could not send event to ('192.168.1.108', 49191), probably stale socket.
```

**Comment by bdraco** [comment]
> Also seeing these from time to time
> 
> ```
> 2020-05-26 22:14:24 DEBUG (Thread-4) [pyhap.accessory_driver] Sending event to client: ('192.168.1.108', 49191)
> 2020-05-26 22:14:24 DEBUG (Thread-4) [pyhap.hap_server] No socket for ('192.168.1.108', 49191)
> 2020-05-26 22:14:24 DEBUG (Thread-4) [pyhap.accessory_driver] Could not send event to ('192.168.1.108', 49191), probably stale socket.
> ```

Those can be expected so hard to tell if its related or not

**Comment by SebasT87** [comment]
> 
> 
> I recently fixed an issue where `zeroconf` announcements would go away after the initial announcement in `0.26.2`
> 
> Can you try upgrading `zeroconf` by changing the version
> in `homeassistant/components/zeroconf/manifest.json` to `0.26.2` and restarting

will give it a try

**Comment by SebasT87** [comment]
Nope.... its regularly gone. Looking into a wireshark now

**Comment by bdraco** [comment]
I've managed to get the race condition to hit.  It looks like my fix in #253 only fixes the write side of the connection.

We may need a bifurcated upgrade to encrypted

**Comment by bdraco** [comment]
Splitting the encryption upgrade process to do the reader first, then send the last response, then upgrade the writer seems to solve it.

Its another suffering from buffering issue

**Comment by bdraco** [comment]
@SebasT87 Can you try the branch here https://github.com/bdraco/HAP-python/tree/split_encryption_upgrade
```
mkdir testing_hap
cd testing_hap
git clone https://github.com/bdraco/HAP-python.git
cd HAP-python
git checkout -t origin/split_encryption_upgrade
pip3 install --upgrade .
```

**Comment by SebasT87** [comment]
Thanks for your hard work!
I've installed this patch but it doesn't solve the problem, although it seems a bit beter. Around 8 of the 10 times it still goes to no response after the connection gets cleaned... 
I have a hunch that cleaning the connection has an unwanted side effect. This seems to result in the device cleaning it's mDNS cache and it has to wait for the next advertisement or response to a query (mDNS is known to be slow at this). Is there any way we can prevent this from happening?

**Comment by SebasT87** [comment]
Using the Discovery App on iOS i can view mDNS on my iPhone

Before connection clean 
![afbeelding](https://user-images.githubusercontent.com/26200470/83013250-fb11d600-a01c-11ea-886f-45247e7f6c72.png)

After connection clean
![afbeelding](https://user-images.githubusercontent.com/26200470/83013288-0b29b580-a01d-11ea-93fd-ba6127f7ddc1.png)

**Comment by bdraco** [comment]
One issue fixed.  Mdns likely has another cause.

Is there and exception or anything interesting  on your console log (not the home-assistant.log) when this happens?

**Comment by bdraco** [comment]
Also there is another new version of zeroconf out today.  You can override the version that comes with Home Assistant with the one that will ship with 0.111 with the following. (I created a test repo with the 0.111 code)

```
cd /config
mkdir custom_components
https://github.com/bdraco/zeroconf.git
```

Restart

**Comment by SebasT87** [comment]
> One issue fixed. Mdns likely has another cause.
> 
> Is there and exception or anything interesting on your console log (not the home-assistant.log) when this happens?

You mean `journalctl -f -u home-assistant`?
There is absolutely nothing in there

**Comment by SebasT87** [comment]
> Also there is another new version of zeroconf out today. You can override the version that comes with Home Assistant with the one that will ship with 0.111 with the following. (I created a test repo with the 0.111 code)
> 
> ```
> cd /config  (or where your configuration.yaml is)
> mkdir custom_components
> cd custom_components
> https://github.com/bdraco/zeroconf.git
> ```
> 
> Restart

Will give this a try. I’ve seen the PR’s in the latest zeroconf but haven’t seen anything that I can relate to the problem... but hey it’s worth the shot

**Comment by SebasT87** [comment]
> 
> 
> Also there is another new version of zeroconf out today. You can override the version that comes with Home Assistant with the one that will ship with 0.111 with the following. (I created a test repo with the 0.111 code)
> 
> ```
> cd /config  (or where your configuration.yaml is)
> mkdir custom_components
> cd custom_components
> https://github.com/bdraco/zeroconf.git
> ```
> 
> Restart

Assuming `https://github.com/bdraco/zeroconf.git` should be `git clone https://github.com/bdraco/zeroconf.git`?

with this zeroconf won't start 

> > Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 175, in _async_setup_component
>     component.setup, hass, processed_config  # type: ignore
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/zeroconf/__init__.py", line 236, in setup
>     HaServiceBrowser(zeroconf, types, handlers=[service_update])
>   File "/usr/local/lib/python3.7/site-packages/zeroconf/__init__.py", line 1393, in __init__
>     if not type_.endswith(service_type_name(type_, allow_underscores=True)):
> AttributeError: 'list' object has no attribute 'endswith'

**Comment by SebasT87** [comment]
changed the manifest.json to version 0.26.3 which should be the latest release. 
Problem remains though.

**Comment by bdraco** [comment]
I'm thinking that either

1. mdns announcement expires and then you see the connection clean because it closes the announcement is gone
2. There is an uncaught exception somewhere and the entire thread is collapsing (thus checking the console log).    There are a few more places logs could end up:

```
# Logs from the supervisor service on the Host OS
journalctl -f -u hassos-supervisor.service

# Supervisor logs
docker logs hassos_supervisor

# Home Assistant logs
docker logs homeassistant
```

**Comment by SebasT87** [comment]
I've looked at the mentioned logs but i couldn't come up with anything interesting unfortunatly.

**Comment by SebasT87** [comment]
I was wondering... is this behaviour even reproduceable at your place? Or is it really just me having trouble

**Comment by bdraco** [comment]
Do you by chance have a unifi router?  
https://help.ui.com/hc/en-us/articles/360001004034-UniFi-Best-Practices-for-Managing-Chromecast-Google-Home-on-UniFi-Network

**Comment by SebasT87** [comment]
I do have a ubi access point but no ubi router. But i checked all multicast related network settings and they seem OK. Also i have Hue connected with Homekit and this works without problems.

**Comment by SebasT87** [comment]
I've been looking at mDNS traffic with Wireshark and there is definitely something fishy going on.
Every query from my device is repeated multiple times and doesn't seem to get a response. Like 10 secs later there seems to be a massive reponse (flood) from Hass.
Queries against normal Homekit hardware (AppleTV for instance) get a single response imediatly.

**Comment by bdraco** [comment]
Do you have an mDNS reflector running somewhere ?

**Comment by SebasT87** [comment]
Not that i'm aware of

**Comment by bdraco** [comment]
I wish I could be more helpful, but I'm out of ideas right now.

**Comment by SebasT87** [comment]
I understand, no problem. You have been very helpfull and i would like to thank you for your effort!

I wil continu my search... and focus on mDNS because i'm convinced that's the cullprit.

**Comment by SebasT87** [comment]
Will close this issue as is does not seem an issue with HAP-python
