### ISSUE TITLE
Allow characteristic properties like minValue to be overridden.

### ISSUE THREAD

**Issue by ikalchev** [ikalchev/HAP-python#26]
It should be possible to configure the properties of a characteristic to align with the functionality of the device and the iOS UI. For example, say your window covering can go up only to 50% open and that it is either closed or open. HAP specifies the default values for the coverings target position as maxValue=100 and minStep=0.1. This means iOS clients can slide at 0.1 step all the way to 100%, which you must map to all-up or all-down in your code.

Instead, you can do:
```python
service = loader.get_serv_loader().get("WindowCovering")
pos = service.get_characteristic("TargetPosition")
pos.properties["maxValue"] = 50
pos.properties["minStep"] = 50
pos.hap_template = pos._create_hap_template()
```

Now iOS correctly allows you to only fully go up or down and the max display value is 50%. The hacky thing about the above is the last line and this is the topic of this issue - overriding properties should be more "native".

**Comment by helmsman35** [comment]
Cool! This is important to properly configure the HomeKit accessories.

I guess a Pos.set_property(“maxValue”, 50) helper methode would be possible. Or even also support a dict as parameter to set multiple properties at once.  The call to _create_hap_template would go in there. I have not looked info the code of that method so I assume here that multiple calls to that method should be possible.

**Comment by ikalchev** [comment]
Yes, correct. I will see which option is the easiest for clients. The whole problems comes from the fact that this hap template is a kind of skeleton dict which is appended to and sent every time to iOS clients. So to avoid computing this on every request, I cache the template, so property changes get left out.

btw another option would be use the dict interface all together and allow only properties defined by HAP:
```python
char["maxValue"] = 100  # ok
char["minStep"] = 2  # ok
char["foo"] = 2  # key error
```

**Comment by helmsman35** [comment]
we must be careful not to do things without thinking.
this is only needed at startup and not at runtime. Setting this in the __init__ of the Accessory

        self.CurrentPosition = self.get_service("WindowCovering").get_characteristic("CurrentPosition")
        self.CurrentPosition.properties["minStep"] = 100

I guess it all depends on when self._set_services is called

**Comment by ikalchev** [comment]
This is one option, but then you need to trigger the create_hap_template or it needs to be generated every time.

To be honest I don't see a problem of it happening during runtime. This is the point of the accessory's config version - say your firmware updates and suddenly you have some new functionality or a way of doing things. So it should be possible to change properties all the time and the interface should take care that the changes are properly presented to iOS (i.e. that it is HAP-compatible)

**Comment by cdce8p** [comment]
Just found this issue. As far as I see it, there aren't any major advantage in using `_create_hap_template`, since copying the template dict in `to_HAP` does take some time as well.

However every attempt to override the properties must happen before the the accessory is paired. That complicates things. I think the best option would be to implement it somewhere in `loader` and read all property changes from a separate file or in the `.state` file.

**Comment by ikalchev** [comment]
This is exactly how I was imagining this initially, but then imagine you need different minValue for different chars instances. In that case creating two files is an overkill and won’t scale well. The hap template solution posted above is how things can work now - it is a hack, and I don’t like it.

Going through the loader has the implication that you need to configure the CharLoader and pass that to the ServiceLoader and it becomes unclear exactly how stuff works. So maybe there should be a way to easily configure after the Acc is created.

**Comment by cdce8p** [comment]
The issue with that is/was that the official docs mention that properties aren't allowed to change after the the accessory is paired. However I had the chance to test it and it seems that in reality it doesn't matter, at least for `min_value` and `max_value`.

I updated the PR to include the `override_properties` method which should make it simpler to update those.
