### ISSUE TITLE
Multiple stream support

### ISSUE THREAD

**Issue by Harryjholmes** [ikalchev/HAP-python#272]
Add RTPStreamManagement to allow multiple devices to view streams at once.

`Wait until someone else in this home stops viewing this camera and try again `

**Comment by bdraco** [comment]
in `pyhap/camera.py` we need multiple `management = self.add_preload_service('CameraRTPStreamManagement')`

Then we need to teach each function to shut down/start the correct stream

**Comment by Harryjholmes** [comment]
https://github.com/home-assistant/core/pull/37968
