### ISSUE TITLE
Unable to install version 3.0.0

### ISSUE THREAD

**Issue by Jornan** [ikalchev/HAP-python#285]
Hello,
According to the documentation the latest versjon is 3.0.0, but when I run the command "pip3 install HAP-python" I only get version 2.9.1. If I try again I get a message saying that requirements are already satisfied (with version 2.9.1) and if I uninstall and re-install I get version 2.9.1 again. 

The total log I get when trying to upgrade is:
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: HAP-python in /usr/local/lib/python3.7/dist-packages (2.9.1)
Requirement already satisfied: ed25519 in ./.local/lib/python3.7/site-packages (from HAP-python) (1.5)
Requirement already satisfied: curve25519-donna in ./.local/lib/python3.7/site-packages (from HAP-python) (1.3)
Requirement already satisfied: zeroconf in ./.local/lib/python3.7/site-packages (from HAP-python) (0.27.1)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from HAP-python) (2.6.1)
Requirement already satisfied: ifaddr in ./.local/lib/python3.7/site-packages (from zeroconf->HAP-python) (0.1.7)

**Comment by applericky** [comment]
I just tried doing this and I downloaded 3.0. This appears to be an issue where your pip is possibly pulling the download. 

Try this.

Download the code and using your favorite terminal app, cd inside the HAP-python-dev folder. once inside do "pip3 install ."

This will look into the setup.py file and install the package.

**Comment by Jornan** [comment]
Thanks, worked like a charm!
