### ISSUE TITLE
Pull latest Apple HAP types. Define overrides.

### ISSUE THREAD

**Issue by ikalchev** [ikalchev/HAP-python#29]
Apple has pushed new Services and Characteristics, which need to be parsed and added to HAP-python using `gen_hap_types.py`.

Also, Apple specifies some non-intuitive default characteristic constraints - for example, by default the CurrentTemperature has a min value of 0, i.e. you cannot report negative values. Thus, there should be a way to override Apple's default values at the end of `gen_hap_types.py`. See pull request #28

**Comment by helmsman35** [comment]
I was looking at the json files in the resources folder for the Speaker service and could not find it. I have checked HAP-NodeJS as I have used that to set the volume on my transceiver when I ran homebridge. 

I have not thoroughly compared everything but I find things missing in the resources jsons

**Comment by ikalchev** [comment]
I know, hence this issue :)
