### ISSUE TITLE
Do not pass `loop` to asyncio.Event

### ISSUE THREAD

**Issue by balloob** [ikalchev/HAP-python#304]
Passing the loop argument to constructors is deprecated in Python 3.8 and will be removed in Python 3.10. You can trigger this as an error now by running the test suite with error on warning:

```
py.test tests/ -Werror -x
```

Making this change would require to remove all passing of / creation of loop in the accessory.

I tried to do this quickly but it means that the accessory needs to be instantiated from inside the event loop, which is not happening inside the tests.

**Comment by bdraco** [comment]
We still support python 3.5 so we need to drop that after https://github.com/ikalchev/HAP-python/pull/301 goes to a release.
