### ISSUE TITLE
self defined Accessories

### ISSUE THREAD

**Issue by Pythonaire** [ikalchev/HAP-python#309]
i have been transcoded a javascript fakegato-history into Python (https://github.com/Pythonaire/FakeGatoHistory). It works good so fare. But, i like to let the pyhap/ressources/characteristics.json and pyhap/ressources/service.json untouched and use my own files or simpler a dictionary for special accessories.
I tried pyhap.loader class and can load the characteristics/services, but can't bind these to my accessory class. Is that possible? Do you have an example for me?

Thx

**Comment by ganonp** [comment]
I'd love an answer to this as well. Is it possible to pass in a custom service dictionary? Or possibly modify the service.json file easily? I know these are predefined services for apple, does this mean we cannot define our own accessories?

**Comment by Pythonaire** [comment]
> I'd love an answer to this as well. Is it possible to pass in a custom service dictionary? Or possibly modify the service.json file easily? I know these are predefined services for apple, does this mean we cannot define our own accessories?

you can, but you have to edit the characteristics.json and services.json. I hoped, were is an easier way.

**Comment by ganonp** [comment]
I actually ended up doing this, and it's not so bad, almost feels like that was sort of the intention. You can copy the originals and then add your own stuff to it (though this can get you in trouble if you are trying to use apple's predefined services, I haven't worked this out entirely yet) and then you can point your loaders to your new amended file.

`loader = Loader(path_char=HAP_PYTHON_CHARACTERISTICS_FILE,
                path_service=HAP_PYTHON_SERVICES_FILE)

driver = AccessoryDriver(port=51826, persist_file=HAP_PYTHON_ACCESSORIES_FILE,
                         loader=loader)`

I suppose you could do something fancy to use their services/cahracteristics and then amend your own so when pyhap is updated you don't have to worry about any changes in their default config, I suspect this is more trouble than it's worth though. I also suspect you've already solved this problem.

**Comment by Pythonaire** [comment]
> I actually ended up doing this, and it's not so bad, almost feels like that was sort of the intention. You can copy the originals and then add your own stuff to it (though this can get you in trouble if you are trying to use apple's predefined services, I haven't worked this out entirely yet) and then you can point your loaders to your new amended file.
> 
> `loader = Loader(path_char=HAP_PYTHON_CHARACTERISTICS_FILE,
> path_service=HAP_PYTHON_SERVICES_FILE)
> 
> driver = AccessoryDriver(port=51826, persist_file=HAP_PYTHON_ACCESSORIES_FILE,
> loader=loader)`
> 
> I suppose you could do something fancy to use their services/cahracteristics and then amend your own so when pyhap is updated you don't have to worry about any changes in their default config, I suspect this is more trouble than it's worth though. I also suspect you've already solved this problem.

**Comment by Pythonaire** [comment]
> I actually ended up doing this, and it's not so bad, almost feels like that was sort of the intention. You can copy the originals and then add your own stuff to it (though this can get you in trouble if you are trying to use apple's predefined services, I haven't worked this out entirely yet) and then you can point your loaders to your new amended file.
> 
> `loader = Loader(path_char=HAP_PYTHON_CHARACTERISTICS_FILE,
> path_service=HAP_PYTHON_SERVICES_FILE)
> 
> driver = AccessoryDriver(port=51826, persist_file=HAP_PYTHON_ACCESSORIES_FILE,
> loader=loader)`
> 
> I suppose you could do something fancy to use their services/cahracteristics and then amend your own so when pyhap is updated you don't have to worry about any changes in their default config, I suspect this is more trouble than it's worth though. I also suspect you've already solved this problem.

Maybe, you are right. i build up my own devices, with a mix of different sensors and actors. Under special circumstances, you can mix services and characteristics. to test the correct display, you have to do some tests. it's easier for me to create my own conf and include it instead of editing in the original. i'll try that. Thanks
