### ISSUE TITLE
HAP-Python 3.4.0 breaks bridge with multiple accessories

### ISSUE THREAD

**Issue by bitaxis** [ikalchev/HAP-python#334]
I have a bridge that consists of two accessories:

- Temperature & humidity sensor
- Motion sensor

Everything was working okay with HAP-Python 3.3.0, the behavior described in ikalchev/HAP-python#327 notwithstanding.

However, after upgrading to HAP-Python 3.4.0, my motion sensor stopped working.  I have an `run()` method defined for each accessory, like below, where it outputs something to the log each time the method is invoked.

```python
@Accessory.run_at_interval(5)
async def run(self): ...
```

My `get_bridge()` method looks like this:

```python
def get_bridge(driver):

    '''
    Call this method to get a Bridge instead of a standalone accessory.
    '''

    bridge = Bridge(driver, 'Study HAP-Python Bridge')
    bridge.set_info_service( ... )

    temp_humid_sensor = TemperatureAndHumiditySensor(driver, 'Temperature & Humidity Sensor')
    bridge.add_accessory(temp_humid_sensor)

    motion_sensor = MotionSensor(driver, 'Motion Sensor')
    bridge.add_accessory(motion_sensor)

    return bridge
```

So I should see some log entry from each accessory every 5 seconds or so when `run()` is invoked.  But with the code as-is, I only see my output from the `temp_humid_sensor` accessory.  I still see `DEBUG` log chatter talking about the motion sensor, but nothing from log entry orchestrated in its `run()` method.

If I comment out the two lines with the `temp_humid_sensor` and restart the service, then I will see the output from my motion sensor accessory.

Also, if I uncomment the two lines and downgrade to HAP-Python 3.3.0, then I once again see output from both accessories every 5 seconds.

I will stick with HAP-Python 3.3.0 for now.

**Comment by bdraco** [comment]
There was a missing await that was fixed in 3.4.0.  Is it possible that it's taking longer than 5s to run?

**Comment by bitaxis** [comment]
Hi, @bdraco.

Not likely.  After seeing you response, I re-upgraded to 3.4.0, restarted my bridge, and let it run for about 10 minutes.  Nothing from the motion sensor, just the temperature/humidity sensor.

Downgraded again to 3.3.0, restarted my bridge, and I get output from both.

**Comment by bdraco** [comment]
> Hi, @bdraco.
> 
> 
> 
> Not likely.  After seeing you response, I re-upgraded to 3.4.0, restarted my bridge, and let it run for about 10 minutes.  Nothing from the motion sensor, just the temperature/humidity sensor.
> 
> 
> 
> Downgraded again to 3.3.0, restarted my bridge, and I get output from both.

Can post the code for the motion sensor that isn't working?

**Comment by bdraco** [comment]
It looks like we can't await in this use case.  I've reverted the change in #335

**Comment by bitaxis** [comment]
Hi, @bdraco.

Here is my code for the Motion sensor accessory:

```python
class MotionSensor(Accessory):

    ERROR_BLINK_INTERVAL = 0.25 # Seconds
    LED_GPIO = 19               # Pin 35
    PIR_SENSOR_GPIO = 23        # Pin 16

    cateogry = CATEGORY_SENSOR

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        serv_motion = self.add_preload_service('MotionSensor')
        self.motion_detected = serv_motion.configure_char('MotionDetected', value=False)
        self.previous_value = None

        self.set_info_service( ... ) # service info redacted

        GPIO.setup(MotionSensor.PIR_SENSOR_GPIO, GPIO.IN)
        GPIO.setup(MotionSensor.LED_GPIO, GPIO.OUT)

    @Accessory.run_at_interval(5)
    async def run(self):

        try:

            current_value = GPIO.input(MotionSensor.PIR_SENSOR_GPIO)
            if current_value != self.previous_value:
                self.motion_detected.set_value(bool(current_value))
                self.previous_value = current_value
                GPIO.output(MotionSensor.LED_GPIO, current_value)
            logging.info('(%s) Motion detected = %s' % (self.display_name, self.motion_detected.value))

        except Exception as ex:

            logging.error(logging.traceback.format_exc())

            for count in range(9):
                GPIO.output(MotionSensor.LED_GPIO, count % 2)
                time.sleep(MotionSensor.ERROR_BLINK_INTERVAL)
```

**Comment by bdraco** [comment]
It looks like this is doing I/O. You should run it in the executor if that’s the case.  Drop the async from the function if it isnt asyncio.  If it is asyncio use await asyncio.sleep instead of time.sleep

**Comment by bitaxis** [comment]
Hmm... Is there an example of how I might go about doing this, @bdraco?

**Comment by bitaxis** [comment]
Okay, after reading through some test code and Python documentation on the [event loop](https://docs.python.org/3.7/library/asyncio-eventloop.html), I re-factored my sensor reading logic into the accessory driver's event loop.  Now my accessories look like what's shown below, along with the `get_bridge()` method.

However, running with HAP-Python 3.4.0, I still don't get any output from my motion sensor, just my temperature/humidity sensor.  But runs just fine with HAP-Python 3.3.2 though.

```python
class MotionSensor(Accessory):

    cateogry = CATEGORY_SENSOR

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        serv_motion = self.add_preload_service('MotionSensor')
        self.motion_detected = serv_motion.configure_char('MotionDetected', value=False)

        self.set_info_service( ... )

    @Accessory.run_at_interval(5)
    def run(self):

        logging.info('(%s) Motion detected = %s' % (self.display_name, self.motion_detected.value))

class TemperatureAndHumiditySensor(Accessory):
    '''
    Combination sensor for both temperature & humidity, like DHT-22
    '''

    cateogry = CATEGORY_SENSOR

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        serv_temp = self.add_preload_service('TemperatureSensor')
        self.current_temperature = serv_temp.configure_char('CurrentTemperature', value=50)

        serv_humidity = self.add_preload_service('HumiditySensor')
        self.current_relative_humidity = serv_humidity.configure_char('CurrentRelativeHumidity', value=50)

        self.set_info_service( ... )

    @Accessory.run_at_interval(5)
    def run(self):

        logging.info('(%s) Temperature = %.1f°F (%.1f°C), humidity = %.1f%%' % (
            self.display_name,
            self.current_temperature.value * 9.0 / 5.0 + 32,
            self.current_temperature.value,
            self.current_relative_humidity.value
            ))

def get_bridge(driver):

    '''
    Call this method to get a Bridge instead of a standalone accessory.
    '''

    bridge = Bridge(driver, 'Study HAP-Python Bridge')
    bridge.set_info_service( ... )

    driver.temp_humid_sensor = TemperatureAndHumiditySensor(driver, 'Temperature & Humidity Sensor')
    bridge.add_accessory(driver.temp_humid_sensor)

    driver.motion_sensor = MotionSensor(driver, 'Motion Sensor')
    bridge.add_accessory(driver.motion_sensor)

    return bridge
```
