### ISSUE TITLE
Garage Door Opener

### ISSUE THREAD

**Issue by jslay88** [ikalchev/HAP-python#35]
Trying to get this working, and it works for the HomeKit requests, but not when the door state changes outside of HomeKit (i.e. when I open the garage with my car remote, instead of HomeKit).

Would like some help troubleshooting this. I am getting the opposite transition state than you would expect, only when the door state changes outside of a HomeKit request from an iOS device.

You can easily simulate this on a RPi, by shorting out a GPIO pin to ground for a `CLOSED` state, and removing from ground for an `OPEN` state. On the iOS, device you can request open, then simulate open, and so forth.

To repro the issue I am having, simply simulate the opposite state of the door, without requesting it from HAP-python.

Also, would like some clarification on how to properly set the initial state of `CurrentDoorState`, as I was seeing some weird things there too, like starting out as `Opening`, even though it was clearly set to `CLOSED`

Here is a simple driver, using pin 17 (BCM)/ 11(BOARD) for the switch, using the new QR stuff of course ;)

```
from pyhap.accessories.GarageDoor import GarageDoor
from pyhap.accessory_driver import AccessoryDriver
import signal


garage = GarageDoor(2, 17, 'GarageDoorTest', pincode=b'920-54-727')
print(garage.display_name)
print(garage.pincode.decode())
garage.print_qr()
driver = AccessoryDriver(garage, port=51826)
signal.signal(signal.SIGINT, driver.signal_handler)
signal.signal(signal.SIGTERM, driver.signal_handler)
driver.start()
```

Please see PR

**Comment by schinckel** [comment]
Oh, oh, oh, I made a garage door opener. You need to do some fancy stuff with target state and current state.

**Comment by jslay88** [comment]
Teach me, obi wan

**Comment by gerswin** [comment]
[https://github.com/gerswin/HAP-python/blob/master/pyhap/accessories/mqtt/GarageDoor.py](url)
check this, maybe can help you

**Comment by ikalchev** [comment]
Closing this as it was already discussed. Keep the conversation open if needed.
