### ISSUE TITLE
AccessoryService information.

### ISSUE THREAD

**Issue by schinckel** [ikalchev/HAP-python#37]
I'm not exactly sure how to override the `AccessoryService` fields: I've tried a bit in my `GarageDoor._set_services()`, but it doesn't seem to work.

I wonder if there should be a way to have this information either pulled from the class, or some other mechanism.

**Comment by schinckel** [comment]
Perhaps a leaf out of the django book: we could have a `get_accessory_information` hook method, that can simply return a dict of data that should be used in the `AccessoryInformation` service.

**Comment by ikalchev** [comment]
Hey I am away for a few hours, will get back to you asap

**Comment by ikalchev** [comment]
Here is a simple example of how it can currently be done:
```python
acc = TemperatureSensor("MyTempSensor")
acc.get_service("AccessoryInformation")\
      .get_characteristic("Manufacturer")\
      .set_value("Foo")
```
You can of course do all this in the `init` or in `_set_services`. However, I like your idea in #41, it has a valid use case.

**Comment by schinckel** [comment]
I had issues with the data not showing up in HomeKit when I override it, but maybe I did something unusual.

**Comment by ikalchev** [comment]
Possible reason: Note that if the Acc is paired with iOS when you make the change, you need to call `config_changed` to trigger iOS clients to re-fetch Characteristics that they don't usually track (alternatively just bump the config_version in the .state and restart). See here for more info: https://github.com/ikalchev/HAP-python/issues/13

**Comment by ikalchev** [comment]
You can now use `add_info_service`
