### ISSUE TITLE
Homeassistant on openwrt - homekit not discovery

### ISSUE THREAD

**Issue by lmahmutov** [ikalchev/HAP-python#390]
When Homeassistant installed on Openwrt and installed Homekit integration i cannot pair with Homekit.
Homekit says that gateway not discovered. 
This problems only when i connecting to openwrt router Wifi, from lan it works normal

**Comment by need2buy** [comment]
workaround for this is to hardcoded the default configured interface under network component of the home assistant installation directory, like what one I have.
/usr/lib/python3.9/site-packages/homeassistant/components/network/const.py

in my case is br-lan ( bridge interface for both wire and wireless )

from 
DEFAULT_CONFIGURED_ADAPTERS: list[str] = []

to
DEFAULT_CONFIGURED_ADAPTERS: list[str] = ["br-lan"]

**Comment by bdraco** [comment]
Why not change the configured interfaces in home assistant in advanced mode ?

**Comment by need2buy** [comment]
I guess under homeassistant you could also configure this via GUI GENERAL SETTING

<img width="600" alt="image" src="https://user-images.githubusercontent.com/78709674/149578332-dd9f5ebd-abf9-4e46-a3ea-6c03867da4d9.png">

**Comment by bdraco** [comment]
Also, you can create your own AsyncZeroconf instance and pass it in with just the interfaces you want it to use

**Comment by lmahmutov** [comment]
> workaround for this is to hardcoded the default configured interface under network component of the home assistant installation directory, like what one I have. /usr/lib/python3.9/site-packages/homeassistant/components/network/const.py
> 
> in my case is br-lan ( bridge interface for both wire and wireless )
> 
> from DEFAULT_CONFIGURED_ADAPTERS: list[str] = []
> 
> to DEFAULT_CONFIGURED_ADAPTERS: list[str] = ["br-lan"]

this solution realy works!
