### ISSUE TITLE
Streaming Question

### ISSUE THREAD

**Issue by ganonp** [ikalchev/HAP-python#400]
Hey guys,

First off, really excellent work on this, I've been using it in a project of my own to build out a hub/sensor/management system specifically for raspberry pi, which you can find [here](https://github.com/ganonp/OpenHub).

My question: I'm trying to get pycam plus raspberry pi zero w to work as a streaming cam for homekit (and add it to the above). I've managed to get the setup to stream pretty flawlessly to a janus webrtc which I can connect to through my browser. But try as I might, I haven't been able to configure the camera accessory to point to the janus server and negotiate the stream (the janus server is running on a different box than the camera / accessory). I dug into this a bit a few months ago and gave up, but since I'm about to start looking at it again I thought I'd check if anyone here could help me with the configuration or even just point me in the right direction.

This is what I'm currently using - note that 192.168.3.101 is the ip of the webrtc server not the address of the raspberry pi which is actually running the camera:

```options = {
            "video": {
                "codec": {
                    "profiles": [
                        VIDEO_CODEC_PARAM_PROFILE_ID_TYPES["BASELINE"],
                        VIDEO_CODEC_PARAM_PROFILE_ID_TYPES["MAIN"],
                        VIDEO_CODEC_PARAM_PROFILE_ID_TYPES["HIGH"]
                    ],
                    "levels": [
                        VIDEO_CODEC_PARAM_LEVEL_TYPES['TYPE3_1'],
                        VIDEO_CODEC_PARAM_LEVEL_TYPES['TYPE3_2'],
                        VIDEO_CODEC_PARAM_LEVEL_TYPES['TYPE4_0'],
                    ],
                },
                "resolutions": [
                    # Width, Height, framerate
                    [320, 240, 15],  # Required for Apple Watch
                    [1024, 768, 30],
                    [640, 480, 30],
                    [640, 360, 30],
                    [480, 360, 30],
                    [480, 270, 30],
                    [320, 240, 30],
                    [320, 180, 30],
                ],
            },
            "audio": {
                "codecs": [
                    {
                        'type': 'OPUS',
                        'samplerate': 24,
                    },
                    {
                        'type': 'AAC-eld',
                        'samplerate': 16
                    }
                ],
            },
            "srtp": False,
            "address": "http://192.168.3.101:8088/janus",
            'start_stream_cmd': ('gst-launch-1.0 v4l2src ! video/x-h264, '
                                 'width=640, '
                                 'height=480, '
                                 'framerate=30/1 '
                                 '! h264parse ! '
                                 'rtph264pay config-interval=1 pt=96 ! '
                                 'udpsink sync=false host=192.168.3.101 port=8004')
        }
```

Any help at all would be greatly appreciated. Thanks!

**Comment by ganonp** [comment]
I think I resolved with a gstreamer command.

https://github.com/ikalchev/HAP-python/issues/403

**Comment by Greg0109** [comment]
Hi @ganonp I have a similar setup to yours except mine points to a mediamtx server which I can see running from VLC, the problem is that I always get a no response camera from HomeKit (as if it couldn't see the rstp server), I tried using gstreamer as well but no luck, is there anyway I could debug further? Cause I have no idea what the problem is
