### ISSUE TITLE
Client attempted pair verify without being paired to Home Assistant Bridge first

### ISSUE THREAD

**Issue by mouth4war** [ikalchev/HAP-python#410]
Pairing an Aqara G2H camera in HASS using homekit integration throws this pyHAP library error after end of pairing and the pairing seemingly fails/resets.

1. Errors in hass log (client attempted pair verify without pairing).
2. Camera shows snapshot for a quick second then goes offline (not responding).
3. HASS notification for Homekit pairing re-appears (suggesting pairing failed or was reset).

https://github.com/home-assistant/core/issues/70157

**Comment by iLuckyW** [comment]
As you closed this issue, were you able to find a solution?
