### ISSUE TITLE
installation hanging

### ISSUE THREAD

**Issue by Pythonaire** [ikalchev/HAP-python#426]
Try to install on a clean system, but it hangs with" Building wheel for cryptography (pyproject.toml) ... /" and CPU = 100%
Following the instructions to update pip didn't help. Renew the system again, the install routine claims it need rust ..
python version is 3.9

**Comment by skoold2003** [comment]
Same problem, even after installing Rust..

**Comment by JKoss2** [comment]
I'm getting the same issue. I installed cryptography manually to install the twilio library and that worked fine (initially, the twilio install threw the same cryptography error, now it doesn't). In fact, when installing `Hap-python[QRCode]`, just like 16 lines above `Collecting cryptography`, which causes the error, it says `Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from HAP-python[QRCode]) (3.3.2)`. 
I don't understand why it's trying to install it again if the requirement is already satisfied. 
And I do not want to manually build using rust.

One weird thing I noticed, in the details of the error it says "n/a" for pip. My pip version is:
`pip 22.3.1 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)`

System Info from error:
          Python: 3.9.2
          platform: Linux-5.15.76-v7+-armv7l-with-glibc2.31
          pip: n/a
          setuptools: 65.6.3
          setuptools_rust: 1.5.2
          rustc: n/a

**Comment by Pythonaire** [comment]
> Try to install on a clean system, but it hangs with" Building wheel for cryptography (pyproject.toml) ... /" and CPU = 100%
> Following the instructions to update pip didn't help. Renew the system again, the install routine claims it need rust ..
> python version is 3.9

in my case, it might be related to the system i tried to install. It was a limited arm6 platform. On arm7 it works.

**Comment by Pythonaire** [comment]
> Try to install on a clean system, but it hangs with" Building wheel for cryptography (pyproject.toml) ... /" and CPU = 100%
> Following the instructions to update pip didn't help. Renew the system again, the install routine claims it need rust ..
> python version is 3.9

reinstall older version works for me: pip install pip3 install --upgrade HAP-python[QRCode]==4.4
