### ISSUE TITLE
Suggestion: HAP-python-min

### ISSUE THREAD

**Issue by cdce8p** [ikalchev/HAP-python#43]
I was thinking if it would make sense to add a new **pypi** project: `HAP-python-min`. This would include all content from `pyhap` except for the `accessories` folder.

I'm currently working on a component for [Home Assistant](https://github.com/home-assistant/home-assistant). Some of the examples form the accessories folder may work, but to port of all functions is basically more difficult than to write a new class which extends `accessory`. Because the initial code base for Home Assistant is already big their is a focus to keep additional imports as small as possible to improve performance. A `min` version would help accomplish that.

**Comment by schinckel** [comment]
I was thinking about this too: whether we package up third-party accessories elsewhere. Perhaps we should/could create a HAP-python team or whatever GitHub calls them, and put packages into there. Could make it easier to have new packages/authors involved, too.

**Comment by ikalchev** [comment]
Okay I will check how to do that, any sharing of know-how is appreciated.

**Comment by jslay88** [comment]
I like this idea about the team and moving accessories elsewhere. I have some pretty specific ones that I would like to include, but feel they are too specific for the main repo.

**Comment by ikalchev** [comment]
Will work on this now.

**Comment by ikalchev** [comment]
For Option B, things will look like this
```
pyhap/
   __init__.py
   ...
   accessories/
      # no __init__.py here; implicit namespace package
      fakes/
         # fake accessories here, e.g. FakeFan, TemperatureSensor
         __init__.py
      sensors/
         # e.g. accessories that measure stuff
         __init__.py
      ...
```
Third-parties can add sub packages to accessories following this directory structure in their repo.

See here https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages.

**Comment by cdce8p** [comment]
I'm no expert on packaging. However I don't think Option C will achive the objectives of this change.

Besides reducing the package size, extracting the accessories to their own repo would make development easier since we can update them for a new version seperately.

Therefore I would prefer either `A` or `B`.

**Comment by ikalchev** [comment]
Done. See `pyhap.accessories.README.md` for integrating as a sub package.
