### ISSUE TITLE
Dehumidifier simple with WaterLevel

### ISSUE THREAD

**Issue by d82k** [ikalchev/HAP-python#445]
Hello, 
I would like to configure a simple custom Dehumidifier with:

- humidity level (the current humidity)
- level of water in the tank

I would like to have something easy just those two indicators and a notification when the water level reaches 95% or above.

In the interface on homekit there are 4 button with the status (auto, humidify, dehumidify, inactive) is there a way to have a plain view as the one show below?

![132054737-e69530d2-cebf-4566-bf6b-2da0b16b9945](https://github.com/ikalchev/HAP-python/assets/2994988/88a8e47f-61fa-40bf-a681-725aad110c54)

I use the following code:

```
class Dehumidifier(Accessory):

    category = CATEGORY_DEHUMIDIFIER

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        serv_dehumidifier = self.add_preload_service('HumidifierDehumidifier', chars=['WaterLevel', 'CurrentRelativeHumidity'])

        self.char_water_level = serv_dehumidifier.configure_char('WaterLevel')
        self.char_humidity = serv_dehumidifier.configure_char('CurrentRelativeHumidity')


    @Accessory.run_at_interval(5)
    def run(self):
        val = random.randint(0, 100)
        self.char_water_level.set_value(val)
        self.char_humidity.set_value(val)
        logging.info("value: %s", val)
```

Any suggestion on the code how to simplify the dehumidifier and add notification on water tank full please?

**Comment by cerahmed** [comment]
I'm looking to implement something similar, any update on this?

**Comment by d82k** [comment]
Hello @cerahmed, 
Appreciate the feedback, I was able finally to look into this and run some tests.
To me still the Auto/Humidifier/Dehumidifier/Standby commands appear under the level. The level is the target humidity, which is editable, current values can be read in the details of the humidifier. Water level can be seen in the details of the dehumidifier, but level cannot be shown as sensor reading (e.g. % of water level in the tank) nor siri does recognize it.

Actions cannot be applied to the level of water, just to humidity as well.

As workaround, I created a leak sensor, and when the water tank is full (being a dehumidifier) I trigger a "water leak" alert. I also forced the leak sensor with a WaterLevel  characteristic also if not accepted can be seen in the details of the leak sensor.

`self.add_preload_service('LeakSensor', chars=['LeakDetected', 'WaterLevel', 'StatusActive'])`

Wondering if there is another way or another sensor which is capable of sending alerts in a customizable way

**Comment by cerahmed** [comment]
Hi @d82k,

The steps I mentioned prevented the Auto/Humidifier/Dehumidifier/Standby options from showing up prior to iOS 17.
I updated to iOS 17 and they showed up again...

If you still see them in iOS 16, you need to remove the device from your home app and re-register them after you apply the steps I suggested.

Indeed, the water level sensor cannot be used for automations, so I attached a fake contact sensor that is set to `open` when a certain percentage is reached.

**Comment by d82k** [comment]
Understood, I was already on iOS 17. 

With the water leakage sensor, it also alerts, is an alternative that with me worked. I guess is not possible so far to tweak it further,,,
