### ISSUE TITLE
Accessory Object parameters

### ISSUE THREAD

**Issue by cdce8p** [ikalchev/HAP-python#45]
The issue regarding https://github.com/home-assistant/home-assistant/pull/12488#discussion_r168964460

As I mentioned above, I personally don't like the way `Hap-python` handles the `__init__` calls for Accessories. At the moment calls look something like this:

### main.py
` acc = TemperatureSensor(display_name='Temperatur')`

### TemperatureSensor(Accessory)
```py
def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
```
Parameter are just being forwarded until Accessory. If you at a wrapper class in between, another level that just forwards the information is introduced.

In python their should be a better way to do this, although that might require some more remodeling. Unfortunately I woun't have time until the next weekend to take a deeper look at it.

**Comment by ikalchev** [comment]
I see what you mean and I agree. I will think how this can be made better.

**Comment by cdce8p** [comment]
I had the time to look at the code. Every option to change this issue would most likely break every implementation that is currently out there and require more mandatory method calls to get started. By now I'm not sure if it would be worth it. If you have an idea, I'm happy to help, but IMO the time would be better spend solving other issues (like #44).

**Comment by cdce8p** [comment]
I think this issue can be closed for now. If there is still a need for it after the complete change to `async` this can be reopened.
