### ISSUE TITLE
Support for customer locks?

### ISSUE THREAD

**Issue by Fluffik3666** [ikalchev/HAP-python#452]
I want to be an able to control my servo and for the accessory to appear as a “lock” in HomeKit? Is this already possible and if so how?

**Comment by oliverwk** [comment]
You should see [this repo](https://github.com/kormax/apple-home-key-reader), which in addition to lock also does some nfc things, but if you don’t want that you can just remove that part.

**Comment by Fluffik3666** [comment]
Tnx!
