### ISSUE TITLE
Stopped working after upgrading to iOS 17

### ISSUE THREAD

**Issue by UnaiUribarri-TomTom** [ikalchev/HAP-python#455]
I have configured a bridge and a single door accessory in home assistant.
They stopped working after updating to iOS 17 my AppleTV & iPhone.

I removed them both from iOS home app and from Home Assistant and tried to reconfigure them as before, but pairing never succeeds. After some minutes, the iPhone shows a message saying that accessory is not reachable and fails.

I am trying to gather the messages from the logs but I recommend avoid upgrading to latest iOS version!

**Comment by oliverwk** [comment]
Same here

**Comment by timchurches** [comment]
Likewise, a bridge application that has worked reliably through multiple upgrades from tvOS and HomePod OS versions 15 and 16 suddenly stopped working after v17 upgrade. Unable to check logs right now (it is at a remote site).
