### ISSUE TITLE
Sphinx Documentation

### ISSUE THREAD

**Issue by jslay88** [ikalchev/HAP-python#46]
Wanted to open an issue to discuss this PR.

We should get some Sphinx (or some other auto-generated documentation) in place now that HA is starting to pick up interest. This will help a lot with new people.

Some basic stuff has been added, wanted to get feedback before I went too deep down the rabbit hole.
It's setup on the ReadTheDocs theme.

**Comment by ikalchev** [comment]
Big big thanks!
