### ISSUE TITLE
Race condition when setting timeout for send event; Document Characteristic.setter_callback

### ISSUE THREAD

**Issue by rodriguez-lucas** [ikalchev/HAP-python#52]
Hi, 

I'm trying to set up a door (`LockMechanism` service) and I'm having this problem: the hap_server responds with timed out.

The door is initially closed and then I tap to open it within the apple's home app.

Here is what I have:

main.py
``` python
"""An example of how to setup and start an Accessory.

This is:
1. Create the Accessory object you want.
2. Add it to an AccessoryDriver, which will advertise it on the local network,
    setup a server to answer client queries, etc.
"""
import logging
import signal

from pyhap.accessories.ElectronicLock import ElectronicLock
from pyhap.accessory import Bridge
from pyhap.accessory_driver import AccessoryDriver

logging.basicConfig(level=logging.DEBUG)

def get_accessory():
    """Call this method to get a standalone Accessory."""
    acc = ElectronicLock("Door")
    return acc

acc = get_accessory()

# Start the accessory on port 51826
driver = AccessoryDriver(acc, port=51826)
# We want KeyboardInterrupts and SIGTERM (kill) to be handled by the driver itself,
# so that it can gracefully stop the accessory, server and advertising.
signal.signal(signal.SIGINT, driver.signal_handler)
signal.signal(signal.SIGTERM, driver.signal_handler)
# Start it!
driver.start()
```

ElectronicLock.py
```python
from pyhap.accessory import Accessory, Category
import pyhap.loader as loader

class LOCK_STATE:
   OPEN = 0
   CLOSED = 1

class ElectronicLock(Accessory):
   category = Category.DOOR

   def __init__(self, *args, **kwargs):
      super(ElectronicLock, self).__init__(*args, **kwargs)

   def set_state(self, value):
      self.get_service("LockMechanism").get_characteristic("LockCurrentState").set_value(value)
      self.get_service("LockMechanism").get_characteristic("LockTargetState").set_value(value, should_callback=False)

   def lock_target_callback(self, value):
      if value == LOCK_STATE.OPEN:
         print("OPEN")
      else:
         print("CLOSED")
      self.set_state(value)

   def _set_services(self):
      super(ElectronicLock, self)._set_services()
      lm_service = loader.get_serv_loader().get("LockMechanism")
      self.add_service(lm_service)
      lm_service.get_characteristic("LockTargetState").setter_callback = self.lock_target_callback

```

terminal log:
```
DEBUG:pyhap.hap_server:Request PUT from address '('192.168.1.100', 54902)' for path '/characteristics'.
INFO:pyhap.hap_server:192.168.1.100 - "PUT /characteristics HTTP/1.1" 207 -
DEBUG:pyhap.hap_server:Request GET from address '('192.168.1.100', 54902)' for path '/characteristics?id=1.8,1.9'.
INFO:pyhap.hap_server:192.168.1.100 - "GET /characteristics?id=1.8,1.9 HTTP/1.1" 207 -
DEBUG:pyhap.hap_server:Request PUT from address '('192.168.1.100', 54902)' for path '/characteristics'.
OPEN
INFO:pyhap.hap_server:192.168.1.100 - "PUT /characteristics HTTP/1.1" 207 -
INFO:pyhap.hap_server:192.168.1.100 - Request timed out: timeout('timed out',)
```

The thing is that after the time out occurs, the server seems to stop listening new requests. I took a look at `HAPServerHandler -> BaseHTTPRequestHandler` but I couldn't find anything.

Any ideas why this is happening?

**Comment by rodriguez-lucas** [comment]
Update:

This may help: [BaseHTTPRequestHandler.py](https://svn.python.org/projects/python/trunk/Lib/BaseHTTPServer.py) (`handle_one_request` method)

I overloaded the method `handle_one_request` in `HAPServerHandler`. 
```python
    def handle_one_request(self):
        """Handle a single HTTP request.

        You normally don't need to override this method; see the class
        __doc__ string for information on how to handle specific HTTP
        commands such as GET and POST.

        """
        try:
            self.raw_requestline = self.rfile.readline()
            if not self.raw_requestline:
                self.close_connection = 1
                return
            if not self.parse_request():
                # An error code has been sent, just exit
                return
            mname = 'do_' + self.command
            if not hasattr(self, mname):
                self.send_error(501, "Unsupported method (%r)" % self.command)
                return
            method = getattr(self, mname)
            method()
            self.wfile.flush() #actually send the response if not already done.
        except socket.timeout, e:
            #a read or a write timed out.  Discard this connection
            self.log_error("Request timed out: %r", e)
            self.close_connection = 1
            return
```
I can confirm that the line: `self.wfile.flush()` is executed but after that a socket.timeout exception occurs.
Another thing I can say is that the exception not always happens.

**Comment by ikalchev** [comment]
Hi @rodriguez-lucas,

The problem in your code is that when `lock_target_callback` is called, the value of the target state is **already** set, i.e. the callback is called after set value sets the value. What roughly happens is:
- iOS updates the target state - triggers `set_value`
- `set_value` (1) sets the value (2) calls the callback and (3) sends the updated value back to iOS

The below works (I reproduced the problem with your previous code):
```python
class LOCK_STATE:
   OPEN = 0
   CLOSED = 1

class ElectronicLock(Accessory):
    category = Category.DOOR

    def __init__(self, *args, **kwargs):
        super(ElectronicLock, self).__init__(*args, **kwargs)
        self.current = self.get_service("LockMechanism").get_characteristic("LockCurrentState")
        self.current.set_value(LOCK_STATE.CLOSED)  # just some initial value.
        self.target = self.get_service("LockMechanism").get_characteristic("LockTargetState")
        self.target.set_value(LOCK_STATE.CLOSED)

    def set_state(self, value):
        self.current.set_value(value)
        #self.target.set_value(value, should_callback=False)  <<< you don't need this

    def lock_target_callback(self, value):
        if value == LOCK_STATE.OPEN:
            print("OPEN")
        else:
            print("CLOSED")
        self.set_state(value)

    def _set_services(self):
        super(ElectronicLock, self)._set_services()
        lm_service = loader.get_serv_loader().get("LockMechanism")
        self.add_service(lm_service)
        lm_service.get_characteristic("LockTargetState").setter_callback = self.lock_target_callback
```

I see a problem in the documentation from my part, so let me change this issue to track that :)

If there is anything more you don't like or need help with, ask here or open an issue.

Best,
Ivan

**Comment by rodriguez-lucas** [comment]
Thanks @ikalchev!

I see your point, that solution (removing the line you said) works. I was aware of it, was on my first comment before I edited it for being so long. 
That said, the reason I was doing that was because I wanted the door to be closed automatically after a timeout, so I had something like this:

(please ignore the timer implementation, the only thing you need to know if that after ~`timeout` seconds  it executes a target function)
```python
from pyhap.accessory import Accessory, Category
import pyhap.loader as loader

import time
from threading import Semaphore, Lock, Thread

class Timer(object):
    def __init__(self, timeout, target_function, target_f_kwargs):
        self.timeout = timeout
        self.time_count_precision = timeout/10
        self.time_lapsed = 0
        self.target_f = target_function
        self.target_f_kwargs = target_f_kwargs

        self.semaphore = Semaphore(0)
        self.mutex = Lock()
        self.thread_worker = Thread(target=self.thread_worker_function, daemon=True)
        self.thread_worker.start()

    def start(self):
        self.semaphore.release()

    def cancel(self):
        self.semaphore.acquire(blocking=False)
        self.mutex.acquire()
        self.time_lapsed = 0
        self.mutex.release()

    def reset(self):
        self.cancel()

    def thread_worker_function(self):
        while True:
            self.semaphore.acquire()

            if self.timeout <= self.time_lapsed:
                self.target_f(**self.target_f_kwargs)
                self.semaphore.release()
                self.reset()
                continue

            self.mutex.acquire()
            self.time_lapsed += self.time_count_precision
            self.mutex.release()

            self.semaphore.release()

            time.sleep(self.time_count_precision)

class LOCK_STATE:
    OPEN = 0
    CLOSED = 1

class ElectronicLock(Accessory):
    category = Category.DOOR

    def __init__(self, *args, **kwargs):
        super(ElectronicLock, self).__init__(*args, **kwargs)

        kwargs = {'value': LOCK_STATE.CLOSED}
        self.timer = Timer(timeout=3, target_function=self.lock_target_callback, target_f_kwargs=kwargs)

        self.current = self.get_service("LockMechanism").get_characteristic("LockCurrentState")
        self.current.set_value(LOCK_STATE.CLOSED)  # just some initial value.
        self.target = self.get_service("LockMechanism").get_characteristic("LockTargetState")
        self.target.set_value(LOCK_STATE.CLOSED)

    def set_state(self, value):
        self.current.set_value(value)
        #self.target.set_value(value, should_callback=False)  <<< now I need this because the timer

    def lock_target_callback(self, value):
        if value == LOCK_STATE.OPEN:
            print("OPEN")
            self.timer.start()
        else:
            print("CLOSED")
            self.timer.cancel()
        self.set_state(value)

    def _set_services(self):
        super(ElectronicLock, self)._set_services()
        lm_service = loader.get_serv_loader().get("LockMechanism")
        self.add_service(lm_service)
        lm_service.get_characteristic("LockTargetState").setter_callback = self.lock_target_callback
```
when the timer ends the `lock_target_callback` is executed with close value, but the target remains unmodified because it wasn't triggered by the phone app, so that was the reason I wanted to update the `LockTargetState` value. 

Although it's quite straight forward solving my problem: calling a different function when the timer ends and updating the values there (`current` and `target`), I'm still confused why I can't force the `target` update. I know that the `target` value was already set by the phone trigger, but if I want to set it again (probably with the same value), why it's not possible?
I don't know if I'm expressing myself correctly. Thanks in advance.

**Comment by ikalchev** [comment]
What follows is a guess, but I am very confident this is exactly what happens:

## Background
When iOS connects to an Accessory, it doesn't close the connection (socket) - it keeps it alive and doesn't say when it leaves (makes sense, because phones move, go to sleep, etc.). It is the accessory's responsibility to "expect" a dead connection.

So using this keep-alive connection, the accessory can send an event, which is what happens when you call `set_value(value, should_notify=True)`. But because the connection could be stale, HAP-python sets a timeout of 3 seconds for the send and if it doesn't happen, it shuts down the connection. After the send the timeout is removed.

On the same connection, iOS can decide to make a HTTP request, such as "set this value to this accessory" and waits for a reply to that request.
## The problem
When I set the timeout to None (i.e. no timeout) instead of 3 seconds, the problem vanishes completely. So I think there is some race condition in which the timeout is not removed properly, which causes a timeout in the thread that makes the request reply. What is more, I think that even if you use the "working" solution of ElectronicLock I posted earlier, there is a chance that it will also timeout.

Thanks for focusing my attention on this - I will try to address this ASAP.

**Comment by rodriguez-lucas** [comment]
I can confirm that the "working" solution sometimes timeouts, and as you said setting timeout to None seems to vanish the problem.

I'll stay tuned and tell if I find sth.

**Comment by ikalchev** [comment]
Fixed. The change is also in pypi (if you don't find 1.1.7, wait for a bit, it sometimes lags).

Let me know if you find any more issues with this or something else :)

**Comment by rodriguez-lucas** [comment]
Nice, I made a quick test and everything seems to be working fine, at least the timeout problem. Thank you.

**Comment by ikalchev** [comment]
No worries. At least the timeout problem? Are there more? :D
