### ISSUE TITLE
Pairing not initiating/completing.

### ISSUE THREAD

**Issue by schinckel** [ikalchev/HAP-python#59]
I'm still hunting down exactly what's going on, but it seems that for some reason I can't successfully pair _any_ HAP-python accessories any longer.

I'm not sure this is something that has changed with our code, as I un-paired and then attempted to re-pair with one that I know worked a couple of weeks ago, but without any luck.

If you check out the repo to `master`, and then run `tox -e temperature`, it should start a server, and show the QR code. In my case, I'm not able to finish the pairing process.

![img_0283](https://user-images.githubusercontent.com/23411/36828108-9277b5d6-1d67-11e8-8da8-78f8681c52c8.jpg)

I've turned logging up to DEBUG, and I don't see the pairing being initiated at all.

**Comment by schinckel** [comment]
I've been comparing this with `homebridge` and I'm not sure I can see any requests coming in to the `HAPServer`.

**Comment by schinckel** [comment]
Works fine after a system restart. Weird.

**Comment by ikalchev** [comment]
I just pulled latest and did `tox -e temperature` and got paired right away (I am on a macOS High Sierra). Perhaps the MAC address that was generated does not appeal to iOS - I had this a few times when testing way before uploading HAP-python to git. Could you try to delete the tox env and restart?

**Comment by ikalchev** [comment]
Glad to hear
