### ISSUE TITLE
add  air pressure sensor support?

### ISSUE THREAD

**Issue by xtqxk** [ikalchev/HAP-python#6]
bme280 support air pressure.

**Comment by ikalchev** [comment]
Hi,

The Services and Characteristic in `pyhap/resources` are those who are officially supported by Apple, i.e. are shown in the iOS Home app and are integrated with Siri.

Air pressure is not officially supported, which means that even if you add it (following the same format for services and chars)., it won't show in the Home app (it used to be like that, I am unaware if this has changed).

Having said that, if you still want to add an air pressure accessory in HAP-python, you can. Some third party manufacturers have done so, but have custom iOS apps.

If something's not clear, please ask :)
