### ISSUE TITLE
[Feature Request] getter callback

### ISSUE THREAD

**Issue by thomaspurchas** [ikalchev/HAP-python#78]
I noticed that in all the example accessories there is always some sort of polling loop updating a char `value`.

I think it would be good to add a `getter_callback` (in addition to the `setter_callback`) that is called when an iOS client requests a char `value`. Then the request can trigger a sensor poll, returning the most recent data, updating the local `value`, and sending any notifications.

This would also remove the need for an explicit polling loop in most cases.

**Comment by ikalchev** [comment]
Sounds good. FYI iOS subscribes for almost all characteristics, so it waits for changes and expects these to be updated without it having to ask for it with a GET request. The only time when iOS does a GET is when you open your Home app or pull your control center and tap on the home icon thingy. This was the reason I decided to go for a more push-y model.

But I def agree - a getter callback can make things simpler for same cases and allows for more choice
