### ISSUE TITLE
Way to add optional chars. to services in Http Accessory

### ISSUE THREAD

**Issue by ikalchev** [ikalchev/HAP-python#9]
Currently, you can use the Http accessory to expose non-hap-compatible devices by allowing them to submit characteristic updates in the form of http post requests.

However, you can only add services with their mandatory characteristics, whereas it should be possible to also add optional chars, such as Name.

This issue tracks the effort for the above.

**Comment by xtqxk** [comment]
Great, i have three esp8266 to report there sensor data.  It will solve my problem。 Thx again.

**Comment by ikalchev** [comment]
I too have a couple of esp8266 which is the exact reason I wrote the Http Accessory :) 

No problem, I hope I finish it by end of the week.

**Comment by ikalchev** [comment]
@xtqxk Update is in, get it with pip3 or git clone it.

Try this:
```python
service_loader = loader.get_serv_loader()
char_loader = loader.get_char_loader()

# Create an accessory with the temperature sensor service with optional characteristic.
# You can add as many accessories to one HttpBridge as you like,
# potentially bridging multiple ESP8266 with one.
# Use the display name to distinguished them in iOS
acc = Accessory("foo", aid=2)  # aid must be unique for all acc. in a bridge
t = service_loader.get("TemperatureSensor")
t.add_opt_characteristic(
   char_loader.get("StatusLowBattery"))
acc.add_service(t)

http_bridge = HttpBridge("HTTP Bridge", address=("", 51111))
http_bridge.add_accessory(acc)
# AccessoryDriver as usual.
```

Then POST to the address as below. Note the aid - Identifies the accessory for which this update is relevant - this is the aid assigned when creating acc.
```json
{
   "aid": 2,    <<<<
   "services": {
      "TemperatureSensor": {
         "CurrentTemperature": 20,
         "StatusLowBattery": true
      }
   }
}
```
I would like to make the `aid` more transparent to the user, but this will come in another update.

Let me know if you hit any problems or have suggestions :)

**Comment by xtqxk** [comment]
Great!
